export const STUDY_DATA = [
  {
    id: 'kaplan-4',
    title: 'Scientific Foundations of Psychology',
    keyTerms: [
      { term: 'Independent Variable (IV)', def: 'The variable the experimenter manipulates to observe its effect; the presumed cause.' },
      { term: 'Dependent Variable (DV)', def: 'The variable measured to see the effect of the IV; the presumed outcome.' },
      { term: 'Confounding Variable', def: 'Any variable other than the IV that could cause changes in the DV, threatening internal validity.' },
      { term: 'Random Assignment', def: 'Placing participants into groups by chance, equalizing pre-existing differences across conditions.' },
      { term: 'Random Sampling', def: 'Selecting participants from a population by chance so results can be generalized.' },
      { term: 'Control Group', def: 'Group that does not receive the experimental treatment; provides a baseline for comparison.' },
      { term: 'Experimental Group', def: 'Group that receives the treatment or manipulation being studied.' },
      { term: 'Double-Blind Study', def: 'Neither participants nor researchers know who is in which group, preventing demand characteristics and experimenter bias.' },
      { term: 'Placebo Effect', def: 'Improvement in the control group due to expectation of treatment rather than an actual treatment.' },
      { term: 'Correlation Coefficient (r)', def: 'A number from −1 to +1 measuring the strength and direction of a linear relationship between two variables.' },
      { term: 'Positive Correlation', def: 'Two variables move in the same direction (both increase or both decrease).' },
      { term: 'Negative Correlation', def: 'Two variables move in opposite directions (one increases as the other decreases).' },
      { term: 'Correlation ≠ Causation', def: 'A statistical relationship between variables does not prove that one causes the other.' },
      { term: 'Case Study', def: 'In-depth investigation of a single individual or small group; high in detail, low in generalizability.' },
      { term: 'Survey', def: 'Self-report questionnaire given to a large group; efficient but subject to social desirability bias.' },
      { term: 'Naturalistic Observation', def: 'Observing behavior in its natural environment without interference.' },
      { term: 'Longitudinal Study', def: 'Following the same participants over a long period to track developmental changes.' },
      { term: 'Cross-Sectional Study', def: 'Comparing different age groups at a single point in time; faster but cohort effects are a concern.' },
      { term: 'Operational Definition', def: 'A precise, measurable definition of how a variable is measured or manipulated in a study.' },
      { term: 'Hypothesis', def: 'A testable prediction about the relationship between variables, derived from theory.' },
      { term: 'Theory', def: 'An explanation that organizes and predicts behaviors or events, supported by repeated findings.' },
      { term: 'Replication', def: 'Repeating a study to verify its findings; essential for scientific reliability.' },
      { term: 'Mean', def: 'The arithmetic average; sensitive to outliers.' },
      { term: 'Median', def: 'The middle score in a distribution; resistant to outliers.' },
      { term: 'Mode', def: 'The most frequently occurring score in a distribution.' },
      { term: 'Standard Deviation', def: 'A measure of how spread out scores are around the mean; larger SD = more variability.' },
      { term: 'Normal Distribution', def: 'A bell-shaped, symmetrical curve where mean = median = mode.' },
      { term: 'Statistical Significance', def: 'A result unlikely to be due to chance (typically p < .05), suggesting a real effect.' },
      { term: 'Informed Consent', def: 'Participants must be told enough about a study to freely agree to participate.' },
      { term: 'Debriefing', def: 'After a study, participants are told the true purpose and any deception is explained.' },
      { term: 'Albert Bandura', def: 'Demonstrated observational learning (social learning theory); Bobo doll experiment showed children imitate aggressive models.' },
      { term: 'Wilhelm Wundt', def: 'Founded the first experimental psychology lab (1879, Leipzig); used introspection.' },
      { term: 'Structuralism', def: 'Wundt and Titchener\'s approach: analyze the structure of conscious experience via introspection.' },
      { term: 'Functionalism', def: 'William James\'s approach: study the purpose (function) of mental processes in adapting to the environment.' },
    ],
    summary: [
      { heading: 'Experimental Method', body: 'The only method that can establish cause-and-effect. Requires: manipulation of IV, measurement of DV, random assignment, and a control group. Both confounding variables and experimenter bias must be controlled — double-blind designs address both.' },
      { heading: 'Correlational Research', body: 'Describes the relationship between variables (r = −1 to +1) but cannot determine causation. Useful when experiments are unethical or impractical. A third variable may explain any observed correlation.' },
      { heading: 'Descriptive Methods', body: 'Case studies provide rich detail for rare phenomena. Surveys reach large samples quickly but suffer from social desirability bias and non-representative samples. Naturalistic observation captures real behavior but cannot control variables.' },
      { heading: 'Statistics', body: 'Measures of central tendency (mean, median, mode) summarize data. Standard deviation measures spread. Normal distributions are bell-shaped. Statistical significance (p < .05) means results are unlikely due to chance, but effect size matters too.' },
      { heading: 'Ethics', body: 'APA ethics code requires: informed consent, the right to withdraw, confidentiality, debriefing, and minimizing harm. Deception is only permissible if necessary and followed by debriefing.' },
      { heading: 'History of Psychology', body: 'Wundt (structuralism) → James (functionalism) → Watson/Skinner (behaviorism) → Freud (psychoanalysis) → Rogers/Maslow (humanism) → modern cognitive/neuroscience perspectives.' },
    ],
    mustKnow: [
      'Only experiments (with random assignment + IV manipulation) establish causation.',
      'Random assignment ≠ random sampling. Assignment → controls for confounds. Sampling → allows generalization.',
      'Correlation coefficient: r = +1 (perfect positive), r = 0 (no relationship), r = −1 (perfect negative).',
      'Double-blind controls both participant expectations (placebo) and researcher bias.',
      'The mean is skewed by outliers; the median is more appropriate for skewed distributions.',
      'Standard deviation: small SD = scores clustered near mean; large SD = scores spread out.',
      'Case study → 1 person; Survey → large sample; Naturalistic obs → real-world behavior.',
      'Bandura\'s Bobo doll: children imitated adult models, showing observational (vicarious) learning.',
      'Debriefing is required after any deception in a study.',
      'A confounding variable provides an alternative explanation for experimental results.',
    ],
    mnemonics: [
      { label: 'IV vs DV', text: 'I **M**anipulate, You **M**easure → IV is what I change, DV is what I observe.\nOr: **D**ependent = **D**ata collected.' },
      { label: 'Research Methods for Causation', text: '**"Only Experiments Cause"** — Observational & correlational studies cannot establish cause-and-effect.' },
      { label: 'Central Tendency Order', text: '**Mean · Median · Mode** — alphabetical order = increasing resistance to outliers.' },
      { label: 'Ethics Steps', text: '**ICDR** — Informed consent → Conduct study → Debrief → Right to withdraw at any time.' },
      { label: 'Correlation Direction', text: 'Positive = **parallel** (both go same way). Negative = **opposite** (one up, one down).' },
    ],
  },

  {
    id: 'kaplan-5',
    title: 'Biological Bases of Behavior',
    keyTerms: [
      { term: 'Neuron', def: 'The basic unit of the nervous system; a specialized cell that transmits electrical and chemical signals.' },
      { term: 'Dendrites', def: 'Branch-like extensions of a neuron that receive incoming signals from other neurons.' },
      { term: 'Axon', def: 'Long fiber that carries the nerve impulse away from the cell body toward the terminal buttons.' },
      { term: 'Myelin Sheath', def: 'Fatty insulating layer around axons that speeds up signal transmission.' },
      { term: 'Action Potential', def: 'The electrical impulse that travels down the axon when a neuron fires; all-or-nothing event.' },
      { term: 'Synapse', def: 'The gap between two neurons across which neurotransmitters travel.' },
      { term: 'Neurotransmitter', def: 'Chemical messenger released into the synapse that binds to receptors on the next neuron.' },
      { term: 'Reuptake', def: 'Process by which neurotransmitters are reabsorbed into the sending neuron after transmission.' },
      { term: 'Acetylcholine (ACh)', def: 'Neurotransmitter involved in muscle movement and memory; deficient in Alzheimer\'s disease.' },
      { term: 'Dopamine', def: 'Involved in reward, motivation, and movement; excess linked to schizophrenia, deficit to Parkinson\'s.' },
      { term: 'Serotonin', def: 'Regulates mood, sleep, and appetite; low levels linked to depression and anxiety.' },
      { term: 'Norepinephrine', def: 'Fight-or-flight neurotransmitter; also involved in alertness and mood.' },
      { term: 'GABA', def: 'Main inhibitory neurotransmitter; reduces neural activity; anti-anxiety drugs enhance GABA.' },
      { term: 'Glutamate', def: 'Main excitatory neurotransmitter; involved in learning and memory.' },
      { term: 'Endorphins', def: 'Natural painkillers released during exercise and stress; produce feelings of euphoria.' },
      { term: 'Frontal Lobe', def: 'Controls executive functions: decision-making, planning, impulse control, voluntary movement (motor cortex).' },
      { term: 'Prefrontal Cortex', def: 'Part of frontal lobe critical for personality, judgment, and social behavior (Phineas Gage case).' },
      { term: 'Parietal Lobe', def: 'Processes somatosensory information (touch, pressure, temperature, pain); contains the somatosensory cortex.' },
      { term: 'Occipital Lobe', def: 'Processes visual information; damage causes visual deficits.' },
      { term: 'Temporal Lobe', def: 'Processes auditory information and language comprehension (Wernicke\'s area); involved in memory.' },
      { term: 'Broca\'s Area', def: 'Located in left frontal lobe; controls speech production. Damage → Broca\'s aphasia (can\'t speak fluently).' },
      { term: 'Wernicke\'s Area', def: 'Located in left temporal lobe; controls language comprehension. Damage → fluent but meaningless speech.' },
      { term: 'Hippocampus', def: 'Critical for forming new long-term memories (explicit/declarative); part of the limbic system.' },
      { term: 'Amygdala', def: 'Processes emotions, especially fear and aggression; involved in emotional memory.' },
      { term: 'Hypothalamus', def: 'Regulates homeostasis: hunger, thirst, body temperature, and the HPA stress axis. Controls the pituitary gland.' },
      { term: 'Thalamus', def: 'Sensory relay station; routes sensory signals to appropriate cortical areas (except smell).' },
      { term: 'Cerebellum', def: 'Coordinates balance, motor movement, and procedural memory.' },
      { term: 'Brain Stem', def: 'Controls basic life functions: breathing, heart rate, sleep/wake cycles (includes medulla and pons).' },
      { term: 'Corpus Callosum', def: 'Thick band of nerve fibers connecting the left and right cerebral hemispheres.' },
      { term: 'Sympathetic Nervous System', def: 'Activates the fight-or-flight response; increases heart rate, dilates pupils, inhibits digestion.' },
      { term: 'Parasympathetic Nervous System', def: 'Promotes rest-and-digest; returns the body to baseline after sympathetic activation.' },
      { term: 'Endocrine System', def: 'System of glands that release hormones into the bloodstream for slower, longer-lasting effects.' },
      { term: 'Cortisol', def: 'Stress hormone released by the adrenal glands during prolonged stress.' },
      { term: 'Heritability', def: 'A statistical measure of how much of the variance in a trait is attributable to genetic differences in a given population.' },
      { term: 'EEG', def: 'Electroencephalogram; records electrical activity across the scalp; useful for studying sleep and seizures.' },
      { term: 'fMRI', def: 'Functional MRI; measures blood flow to show which brain areas are active during tasks; best spatial resolution.' },
    ],
    summary: [
      { heading: 'Neural Communication', body: 'Neurons receive signals via dendrites, integrate them at the cell body, and fire action potentials down the axon. Neurotransmitters cross the synapse to bind to receptors on the next neuron. Agonists mimic neurotransmitters; antagonists block them. Reuptake removes excess neurotransmitters.' },
      { heading: 'Brain Lobes & Functions', body: 'Frontal (executive, motor), Parietal (somatosensory), Temporal (auditory, language comprehension, memory), Occipital (visual). Broca\'s area (speech production) is in the frontal lobe; Wernicke\'s area (comprehension) is in the temporal lobe.' },
      { heading: 'Limbic System', body: 'The emotional brain: amygdala (fear/emotions), hippocampus (new memories), hypothalamus (homeostasis/drives), thalamus (sensory relay). The limbic system sits below the cortex and above the brain stem.' },
      { heading: 'Autonomic Nervous System', body: 'The ANS operates automatically. Sympathetic = fight-or-flight (uses norepinephrine/epinephrine). Parasympathetic = rest-and-digest. They are antagonistic: when one is active the other is inhibited.' },
      { heading: 'Genetics & Behavior', body: 'Heritability studies (twin, adoption) separate genetic from environmental contributions. High heritability does not mean a trait is fixed — environment still shapes expression. Nature and nurture interact.' },
    ],
    mustKnow: [
      'Frontal lobe = higher-order thinking, impulse control, voluntary motor movement.',
      'Phineas Gage — prefrontal cortex damage → personality change (impulsive, irresponsible).',
      'Hippocampus = explicit memory formation; Amygdala = emotional (especially fear) memory.',
      'Broca\'s aphasia = can understand, cannot produce fluent speech (frontal lobe).',
      'Wernicke\'s aphasia = fluent but nonsensical speech (temporal lobe).',
      'Sympathetic NS: fight-or-flight. Parasympathetic NS: rest-and-digest.',
      'Dopamine excess → schizophrenia; Dopamine deficit → Parkinson\'s.',
      'Serotonin deficit → depression/anxiety; SSRIs block serotonin reuptake.',
      'ACh deficit → Alzheimer\'s disease; GABA = inhibitory; Glutamate = excitatory.',
      'fMRI shows brain activity (blood flow); EEG shows electrical activity over time.',
    ],
    mnemonics: [
      { label: 'Lobes Clockwise', text: '**"Frontal, Parietal, Occipital, Temporal"** → **F**ront to back on top, then **T**emple on the side.\nRemember: **F**unny **P**eople **O**ften **T**alk.' },
      { label: 'Sympathetic vs Parasympathetic', text: '**Sympathetic = Stress** (fight-or-flight). **Parasympathetic = Peace** (rest-and-digest).' },
      { label: 'Dopamine disorders', text: '**"Too much D = Delusions (schizophrenia), Too little D = Dragging (Parkinson\'s)"**' },
      { label: 'ACh & Alzheimer\'s', text: '**ACh → Alzheimer\'s** — both start with "A." ACh deficit = memory loss.' },
      { label: 'Broca vs Wernicke', text: '**Broca = Broken speech** (can\'t produce). **Wernicke = Word salad** (can\'t understand).' },
    ],
  },

  {
    id: 'kaplan-6',
    title: 'Sensation and Perception',
    keyTerms: [
      { term: 'Sensation', def: 'Detection of physical energy by sensory organs; the raw data from the senses.' },
      { term: 'Perception', def: 'The brain\'s interpretation and organization of sensory information into meaningful patterns.' },
      { term: 'Absolute Threshold', def: 'The minimum intensity of a stimulus needed to detect it 50% of the time.' },
      { term: 'Difference Threshold (JND)', def: 'Just-noticeable difference; the minimum change in stimulus intensity detectable 50% of the time.' },
      { term: 'Weber\'s Law', def: 'The JND is a constant proportion of the original stimulus intensity (e.g., ~2% for weight).' },
      { term: 'Signal Detection Theory', def: 'Detection of a stimulus depends on both its intensity and the observer\'s psychological state (expectations, fatigue).' },
      { term: 'Sensory Adaptation', def: 'Decreased sensitivity to a constant stimulus over time (e.g., getting used to a smell).' },
      { term: 'Transduction', def: 'Conversion of physical stimulus energy into neural signals the brain can interpret.' },
      { term: 'Rods', def: 'Photoreceptors in the retina sensitive to dim light; used for peripheral and night vision; no color.' },
      { term: 'Cones', def: 'Photoreceptors concentrated in the fovea; detect color and fine detail; require bright light.' },
      { term: 'Fovea', def: 'Central region of the retina with the highest density of cones; point of sharpest vision.' },
      { term: 'Optic Nerve', def: 'Carries visual signals from the retina to the brain; creates the blind spot where it exits.' },
      { term: 'Trichromatic Theory', def: 'Young-Helmholtz: color vision relies on three types of cones (red, green, blue); explains most color mixing.' },
      { term: 'Opponent-Process Theory', def: 'Hering: color vision uses opponent pairs (red-green, blue-yellow, black-white); explains afterimages.' },
      { term: 'Cochlea', def: 'Fluid-filled snail-shaped structure in the inner ear; hair cells here transduce sound waves into neural signals.' },
      { term: 'Place Theory', def: 'Different pitches cause vibration at different places on the basilar membrane; explains high-frequency sounds.' },
      { term: 'Frequency Theory', def: 'The basilar membrane fires at the same rate as the sound wave; explains low-frequency sounds.' },
      { term: 'Gestalt Principles', def: 'Rules the brain uses to organize sensory information into coherent wholes (figure-ground, proximity, similarity, closure, continuity).' },
      { term: 'Figure-Ground', def: 'The tendency to perceive one part of a scene as the figure (foreground) and the rest as background.' },
      { term: 'Closure', def: 'Gestalt principle: we perceive incomplete figures as whole by filling in missing information.' },
      { term: 'Depth Perception', def: 'Ability to judge distance and see in three dimensions; relies on binocular cues and monocular cues.' },
      { term: 'Binocular Disparity', def: 'Depth cue from the difference between the two retinal images (eyes are ~6 cm apart).' },
      { term: 'Monocular Cues', def: 'Depth cues available to one eye: linear perspective, interposition, texture gradient, relative size.' },
      { term: 'Gate-Control Theory', def: 'Melzack & Wall: the spinal cord contains a "gate" that can be opened or closed to pain signals; explains why rubbing an injury helps.' },
      { term: 'Vestibular Sense', def: 'Sense of balance and spatial orientation; receptors are in the semicircular canals of the inner ear.' },
      { term: 'Kinesthesis', def: 'Sense of body position and movement of limbs; receptors are in muscles, tendons, and joints.' },
      { term: 'Top-Down Processing', def: 'Perception driven by prior knowledge, expectations, and context (from brain to senses).' },
      { term: 'Bottom-Up Processing', def: 'Perception built from raw sensory data without prior knowledge (from senses to brain).' },
    ],
    summary: [
      { heading: 'Vision Pathway', body: 'Light → cornea → pupil → lens → retina (rods & cones) → optic nerve → thalamus → occipital cortex. Rods: dim light/periphery. Cones: color/detail/fovea. Two color theories work together: trichromatic at the receptor level, opponent-process at higher levels.' },
      { heading: 'Hearing Pathway', body: 'Sound waves → outer ear → eardrum → ossicles (hammer, anvil, stirrup) → oval window → cochlea → auditory nerve → temporal cortex. Place theory explains high pitches; frequency theory explains low pitches.' },
      { heading: 'Psychophysics', body: 'Absolute threshold = minimum detectable level. JND = smallest noticeable change. Weber\'s Law: JND is proportional to stimulus magnitude. Signal detection theory adds observer factors beyond pure stimulus strength.' },
      { heading: 'Perceptual Organization', body: 'Gestalt principles: figure-ground, proximity, similarity, closure, continuity, common fate. Top-down processing uses expectations; bottom-up uses raw data. Perceptual constancy (size, shape, color) maintains stable perception despite changing sensory input.' },
    ],
    mustKnow: [
      'Rods = dim light, peripheral, black-and-white. Cones = bright light, fovea, color.',
      'Trichromatic = three cone types → color mixing. Opponent-process → afterimages.',
      'Absolute threshold = 50% detection. JND = 50% change detection.',
      'Weber\'s Law: JND is a constant % of original stimulus.',
      'Gestalt closure = filling in gaps. Figure-ground = separating object from background.',
      'Binocular disparity = depth from two eyes. Linear perspective = monocular depth cue.',
      'Place theory = high-freq sounds. Frequency theory = low-freq sounds.',
      'Gate-control theory: spinal gate modulates pain; explains why touch reduces pain.',
      'Vestibular = balance (inner ear). Kinesthesis = body position (joints/muscles).',
      'Top-down = expectation-driven. Bottom-up = data-driven.',
    ],
    mnemonics: [
      { label: 'Rods vs Cones', text: '**Rods = Radar** (work in the dark, everywhere). **Cones = Color** (need light, in center/fovea).' },
      { label: 'Color Vision Theories', text: '**Tri**chromatic = **Tri**angle of 3 cones. **Opponent** = afterimages (stare at green, see red).' },
      { label: 'Ear Bones', text: '**"Hammer, Anvil, Stirrup"** → They look like blacksmith tools. In order: malleus → incus → stapes.' },
      { label: 'Gestalt Principles', text: '**"People Sickeningly Close Figure Ground"** → Proximity, Similarity, Closure, Figure-ground, Good continuation.' },
      { label: 'Top-down vs Bottom-up', text: '**Top-down = Thinking** (brain drives it). **Bottom-up = Building** (sensors drive it).' },
    ],
  },

  {
    id: 'kaplan-7',
    title: 'Learning',
    keyTerms: [
      { term: 'Classical Conditioning', def: 'Pavlov: learning by association — a neutral stimulus becomes a conditioned stimulus when paired repeatedly with an unconditioned stimulus.' },
      { term: 'Unconditioned Stimulus (UCS)', def: 'A stimulus that naturally and automatically triggers a response (e.g., food).' },
      { term: 'Unconditioned Response (UCR)', def: 'The natural, unlearned response to the UCS (e.g., salivation to food).' },
      { term: 'Conditioned Stimulus (CS)', def: 'A previously neutral stimulus that, after association with the UCS, triggers a conditioned response (e.g., bell).' },
      { term: 'Conditioned Response (CR)', def: 'The learned response to the CS (usually similar to the UCR, e.g., salivation to bell).' },
      { term: 'Acquisition', def: 'The initial learning of a stimulus-response association; CS and UCS must be paired contiguously.' },
      { term: 'Extinction', def: 'Weakening of a CR when the CS is repeatedly presented without the UCS.' },
      { term: 'Spontaneous Recovery', def: 'After extinction, the CR reappears when the CS is presented again after a rest period.' },
      { term: 'Generalization', def: 'Responding to stimuli similar to the CS (e.g., fearing all dogs after being bitten by one).' },
      { term: 'Discrimination', def: 'Learned ability to distinguish the CS from similar stimuli; opposite of generalization.' },
      { term: 'Aversion Therapy', def: 'Classical conditioning technique pairing an undesirable behavior with an aversive stimulus to eliminate it (e.g., pairing alcohol with nausea).' },
      { term: 'Operant Conditioning', def: 'Skinner: learning in which behavior is strengthened or weakened by its consequences (reinforcements/punishments).' },
      { term: 'Reinforcement', def: 'Any consequence that increases the likelihood of a behavior being repeated.' },
      { term: 'Positive Reinforcement', def: 'Adding a pleasant stimulus after a behavior to increase it (e.g., giving a treat).' },
      { term: 'Negative Reinforcement', def: 'Removing an aversive stimulus after a behavior to increase it (e.g., taking aspirin to relieve pain).' },
      { term: 'Positive Punishment', def: 'Adding an aversive stimulus after a behavior to decrease it (e.g., a speeding ticket).' },
      { term: 'Negative Punishment', def: 'Removing a pleasant stimulus after a behavior to decrease it (e.g., taking away a phone).' },
      { term: 'Fixed-Ratio Schedule', def: 'Reinforcement after a set number of responses; produces high, steady rates with a brief pause after each reward.' },
      { term: 'Variable-Ratio Schedule', def: 'Reinforcement after an unpredictable number of responses; produces highest and most consistent response rates (slot machines).' },
      { term: 'Fixed-Interval Schedule', def: 'Reinforcement after a set amount of time; produces scallop-shaped response pattern (slow then fast near reward time).' },
      { term: 'Variable-Interval Schedule', def: 'Reinforcement after unpredictable time intervals; produces slow, steady responding (e.g., checking email).' },
      { term: 'Shaping', def: 'Operant technique: rewarding successive approximations of the desired behavior.' },
      { term: 'Observational Learning', def: 'Bandura: learning by watching and imitating others (models).' },
      { term: 'Vicarious Reinforcement', def: 'Learning is strengthened when we observe a model being rewarded for a behavior.' },
      { term: 'Latent Learning', def: 'Tolman: learning that is not immediately reflected in behavior; occurs without reinforcement (e.g., cognitive maps).' },
      { term: 'Insight Learning', def: 'Köhler: sudden understanding of a problem\'s solution without explicit trial and error.' },
      { term: 'Learned Helplessness', def: 'Seligman: after repeated unavoidable aversive events, an organism gives up and stops trying to escape, even when escape becomes possible.' },
    ],
    summary: [
      { heading: 'Classical Conditioning', body: 'Pavlov\'s dogs: bell (NS) paired with food (UCS) → bell becomes CS → salivation (CR). Key processes: acquisition (pairing), extinction (CS alone), spontaneous recovery (CR returns after rest), generalization, discrimination. Used clinically in aversion therapy and systematic desensitization.' },
      { heading: 'Operant Conditioning', body: 'Skinner\'s box: behavior followed by a consequence. Reinforcement increases behavior (positive adds, negative removes aversive). Punishment decreases behavior (positive adds aversive, negative removes pleasant). Schedules: variable-ratio is most resistant to extinction; fixed-interval produces scallop pattern.' },
      { heading: 'Cognitive & Social Learning', body: 'Bandura showed learning can occur through observation (Bobo doll). Tolman\'s latent learning shows organisms build cognitive maps without reward. Köhler\'s chimps showed insight — sudden "aha" moments. Seligman\'s learned helplessness: repeated uncontrollable bad events produce passivity (model for depression).' },
    ],
    mustKnow: [
      'Classical conditioning: UCS → UCR (natural). CS → CR (learned). NS + UCS → CS.',
      'Negative reinforcement ≠ punishment. Negative reinforcement REMOVES something bad to INCREASE behavior.',
      'Variable-ratio schedule is most resistant to extinction (slot machines).',
      'Fixed-interval scallop: response rate accelerates near the reward time.',
      'Bandura: observational learning requires attention, retention, reproduction, motivation.',
      'Learned helplessness: repeated uncontrollable shocks → animal stops trying even when escape is possible.',
      'Aversion therapy = classical conditioning pairing behavior with unpleasant stimulus.',
      'Shaping = reinforcing successive approximations toward target behavior.',
      'Extinction ≠ forgetting. Spontaneous recovery proves the association is not fully erased.',
      'Latent learning occurs without explicit reinforcement; cognitive maps stored until needed.',
    ],
    mnemonics: [
      { label: 'CC vs OC', text: '**Classical** = **Cueing** (stimulus triggers response automatically). **Operant** = **Outcomes** (consequences shape behavior).' },
      { label: 'Reinforcement vs Punishment', text: '**R** = behavior **R**ises. **P** = behavior **P**lunges.\n**Positive** = add something. **Negative** = remove something.' },
      { label: 'Schedules of Reinforcement', text: '**"VR = Vegas Rule"** — slot machines, variable ratio, hardest to extinguish.\n**Fixed-Interval scallop** = slow then fast, like studying before an exam.' },
      { label: 'Bandura\'s 4 Steps', text: '**ARRM** — **A**ttention → **R**etention → **R**eproduction → **M**otivation.' },
      { label: 'Pavlov\'s Order', text: '**NS → UCS/UCR → CS → CR**: "Nothing Unusual, Until Conditioning Resolves."' },
    ],
  },

  {
    id: 'kaplan-8',
    title: 'Cognitive Psychology',
    keyTerms: [
      { term: 'Cognition', def: 'Mental activities associated with thinking, knowing, remembering, and communicating.' },
      { term: 'Encoding', def: 'Getting information into memory; can be automatic or effortful (deep = semantic; shallow = visual/acoustic).' },
      { term: 'Storage', def: 'Retaining encoded information over time.' },
      { term: 'Retrieval', def: 'Getting stored information out of memory; cued recall > free recall.' },
      { term: 'Sensory Memory', def: 'Very brief (fraction of a second to seconds) storage of sensory input. Iconic (visual) and echoic (auditory).' },
      { term: 'Short-Term Memory (STM)', def: 'Limited-capacity memory (~7±2 items) lasting ~20–30 seconds without rehearsal.' },
      { term: 'Working Memory', def: 'Baddeley\'s updated model of STM; active manipulation and processing of information.' },
      { term: 'Long-Term Memory (LTM)', def: 'Relatively permanent, unlimited-capacity memory storage.' },
      { term: 'Explicit (Declarative) Memory', def: 'Conscious memory for facts (semantic) and events (episodic); requires hippocampus.' },
      { term: 'Semantic Memory', def: 'Memory for general facts and knowledge (e.g., capitals of countries).' },
      { term: 'Episodic Memory', def: 'Memory for personal experiences and events tied to specific time and place.' },
      { term: 'Implicit Memory', def: 'Unconscious memory for skills and conditioned responses; includes procedural memory and priming.' },
      { term: 'Procedural Memory', def: 'Memory for how to perform motor skills (riding a bike); stored in cerebellum/basal ganglia.' },
      { term: 'Priming', def: 'Exposure to a stimulus influences responses to a later stimulus, often without awareness.' },
      { term: 'Chunking', def: 'Organizing information into meaningful units to increase STM capacity.' },
      { term: 'Elaborative Rehearsal', def: 'Deep processing by linking new information to existing knowledge; more effective than rote repetition.' },
      { term: 'Spacing Effect', def: 'Distributing study over time produces better retention than massed practice (cramming).' },
      { term: 'Serial Position Effect', def: 'Better recall for items at the beginning (primacy) and end (recency) of a list.' },
      { term: 'Proactive Interference', def: 'Old information interferes with learning/recalling new information.' },
      { term: 'Retroactive Interference', def: 'New information interferes with recall of old information.' },
      { term: 'Repression', def: 'Freud: motivated forgetting of traumatic or anxiety-provoking memories.' },
      { term: 'Misinformation Effect', def: 'Loftus: post-event misleading information alters the memory of an event.' },
      { term: 'Functional Fixedness', def: 'Cognitive bias to see objects only in their usual function, blocking creative problem solving.' },
      { term: 'Confirmation Bias', def: 'Tendency to search for and favor information that confirms preexisting beliefs.' },
      { term: 'Availability Heuristic', def: 'Judging probability based on how easily examples come to mind.' },
      { term: 'Representativeness Heuristic', def: 'Judging by how closely something matches a mental prototype or category.' },
      { term: 'Fluid Intelligence', def: 'Cattell: the capacity to think logically and solve novel problems; declines with age.' },
      { term: 'Crystallized Intelligence', def: 'Cattell: accumulated knowledge and verbal skills; increases with age and experience.' },
      { term: 'g Factor', def: 'Spearman\'s general intelligence factor underlying all cognitive abilities.' },
      { term: 'Multiple Intelligences', def: 'Gardner: at least 8 distinct intelligences (linguistic, logical-mathematical, spatial, musical, bodily-kinesthetic, interpersonal, intrapersonal, naturalist).' },
      { term: 'Normal Distribution of IQ', def: 'IQ is bell-shaped with mean = 100, SD = 15. 68% of scores fall between 85–115.' },
    ],
    summary: [
      { heading: 'Memory Stages', body: 'Atkinson-Shiffrin model: sensory → STM → LTM. Encoding → Storage → Retrieval. Deep (semantic) encoding produces better retention than shallow (acoustic/visual) encoding. Spacing, testing, and elaboration improve long-term retention.' },
      { heading: 'Types of Long-Term Memory', body: 'Explicit: facts (semantic) and personal events (episodic) — hippocampus-dependent. Implicit: skills (procedural — cerebellum) and priming. Explicit memories can be verbalized; implicit usually cannot.' },
      { heading: 'Forgetting', body: 'Encoding failure (never stored). Storage decay. Retrieval failure (tip-of-tongue). Interference: proactive (old blocks new), retroactive (new blocks old). Misinformation effect: eyewitness memory is reconstructive, not like a video recording.' },
      { heading: 'Problem Solving & Heuristics', body: 'Algorithms guarantee a solution but are slow. Heuristics are mental shortcuts — fast but error-prone. Availability = what comes to mind easily. Representativeness = prototype matching. Confirmation bias distorts evaluation. Functional fixedness blocks creative solutions.' },
      { heading: 'Intelligence', body: 'Spearman: g factor (general) + specific abilities. Cattell: fluid (novel) vs crystallized (acquired). Gardner: 8 multiple intelligences. IQ = bell curve, mean 100, SD 15. IQ tests measure g but also reflect opportunity and education.' },
    ],
    mustKnow: [
      'STM capacity: ~7±2 items; duration ~20-30 sec without rehearsal.',
      'Episodic memory = personal events; Semantic = general knowledge; both are explicit.',
      'Procedural memory (implicit) survives hippocampal damage (H.M. case).',
      'Serial position: primacy (first items) = LTM. Recency (last items) = STM.',
      'Proactive interference: OLD blocks NEW. Retroactive: NEW blocks OLD.',
      'Misinformation effect (Loftus): memory is reconstructive, not reproductive.',
      'Functional fixedness = can only see an object\'s typical use.',
      'Availability heuristic: plane crashes feel more likely than car crashes after media coverage.',
      'Fluid intelligence: declines with age. Crystallized: increases with experience.',
      'Normal IQ distribution: mean 100, SD 15; 68% between 85-115.',
    ],
    mnemonics: [
      { label: 'Interference Types', text: '**Pro = Pro-forward** (old info goes forward and disrupts new). **Retro = Retro-backward** (new info reaches back and disrupts old).\nOr: **"PORN"** — **P**ro-active, **O**ld interferes with **N**ew.' },
      { label: 'Serial Position', text: '**Primacy = LTM** (had time to rehearse). **Recency = STM** (still in working memory).' },
      { label: 'Explicit vs Implicit', text: '**Explicit = Explain** it (can verbalize). **Implicit = Involuntary** (automatic, hard to describe).' },
      { label: 'Fluid vs Crystallized', text: '**Fluid = Flowing** (flexible, novel, youth). **Crystallized = Crystal = formed over time** (experience, grows with age).' },
      { label: 'Heuristics', text: '**Availability = "A"wareness** (what pops into mind). **Representativeness = "R"esemblance** (matches prototype?).' },
    ],
  },

  {
    id: 'kaplan-9',
    title: 'Developmental Psychology',
    keyTerms: [
      { term: 'Jean Piaget', def: 'Proposed four stages of cognitive development: sensorimotor, preoperational, concrete operational, formal operational.' },
      { term: 'Schema', def: 'A mental framework or category that organizes and interprets information.' },
      { term: 'Assimilation', def: 'Fitting new information into an existing schema.' },
      { term: 'Accommodation', def: 'Modifying an existing schema or creating a new one to incorporate new information.' },
      { term: 'Sensorimotor Stage (0–2 yrs)', def: 'Piaget: infants learn through senses and motor actions; object permanence develops by ~8 months.' },
      { term: 'Object Permanence', def: 'Understanding that objects continue to exist even when not visible; develops ~8–12 months.' },
      { term: 'Preoperational Stage (2–7 yrs)', def: 'Piaget: symbolic thinking develops; egocentrism; lacks conservation; animism.' },
      { term: 'Egocentrism', def: 'Preoperational child\'s inability to see the world from another\'s perspective (Piaget\'s three mountains task).' },
      { term: 'Conservation', def: 'Understanding that quantity remains the same despite changes in shape or appearance; develops in concrete operational stage.' },
      { term: 'Concrete Operational Stage (7–12 yrs)', def: 'Piaget: logical reasoning about concrete objects; mastery of conservation and classification.' },
      { term: 'Formal Operational Stage (12+)', def: 'Piaget: abstract and hypothetical reasoning; systematic problem solving.' },
      { term: 'Zone of Proximal Development (ZPD)', def: 'Vygotsky: the gap between what a child can do alone and what they can do with guidance from a more skilled person.' },
      { term: 'Scaffolding', def: 'Vygotsky: temporary support provided by a more skilled person that is gradually withdrawn as the learner develops competence.' },
      { term: 'Theory of Mind', def: 'The understanding that others have thoughts, feelings, and perspectives different from one\'s own; develops ~age 4.' },
      { term: 'Attachment', def: 'Ainsworth: deep emotional bond between infant and caregiver; tested with the Strange Situation.' },
      { term: 'Secure Attachment', def: 'Infant uses caregiver as a safe base; distressed when caregiver leaves, happy when they return; most common and adaptive.' },
      { term: 'Insecure-Avoidant Attachment', def: 'Infant shows little distress at separation and ignores caregiver on return; associated with consistently unavailable caregivers.' },
      { term: 'Insecure-Anxious/Ambivalent Attachment', def: 'Infant is extremely distressed at separation and ambivalent (angry/clingy) on return; associated with inconsistent caregiving.' },
      { term: 'Disorganized Attachment', def: 'No consistent strategy; often linked to abusive or frightening caregiving.' },
      { term: 'Imprinting', def: 'Lorenz: rapid attachment formed during a critical period early in life (e.g., ducklings following the first moving object).' },
      { term: 'Critical Period', def: 'A biologically determined window of time during which specific learning or development must occur.' },
      { term: 'Erikson\'s Psychosocial Stages', def: 'Eight stages spanning the life course, each involving a psychosocial crisis (e.g., trust vs. mistrust in infancy).' },
      { term: 'Kohlberg\'s Moral Development', def: 'Three levels: preconventional (self-interest), conventional (rules/norms), postconventional (principles).' },
      { term: 'Preconventional Morality', def: 'Kohlberg Level 1: moral decisions based on consequences to oneself (punishment/reward).' },
      { term: 'Conventional Morality', def: 'Kohlberg Level 2: moral decisions based on rules, laws, and social norms.' },
      { term: 'Postconventional Morality', def: 'Kohlberg Level 3: moral decisions based on abstract ethical principles that may transcend laws.' },
      { term: 'Temperament', def: 'Inborn, stable predispositions toward emotional reactivity; shapes personality development.' },
      { term: 'Continuity vs Discontinuity', def: 'Debate over whether development is gradual (continuity) or occurs in distinct stages (discontinuity).' },
    ],
    summary: [
      { heading: 'Piaget\'s Cognitive Stages', body: 'Sensorimotor (0–2): object permanence. Preoperational (2–7): symbolic thought, egocentrism, no conservation. Concrete operational (7–12): conservation, logical thinking about tangible things. Formal operational (12+): abstract/hypothetical reasoning. Piaget underestimated children\'s abilities and ignored social context.' },
      { heading: 'Vygotsky\'s Social Development', body: 'Learning is social. ZPD = the gap between current ability and potential with help. Scaffolding provides the support to bridge that gap. Private speech (talking to oneself) guides cognition. Vygotsky emphasized culture and language more than Piaget.' },
      { heading: 'Attachment Theory', body: 'Ainsworth\'s Strange Situation revealed four attachment styles. Secure (caregiver is responsive) → healthiest outcomes. Harlow\'s monkeys showed contact comfort (not just feeding) creates attachment. Imprinting (Lorenz) shows critical periods for bonding in animals.' },
      { heading: 'Moral Development', body: 'Kohlberg: preconventional (self-interest) → conventional (rules) → postconventional (principles). Most adults operate at conventional level. Gilligan critiqued Kohlberg for gender bias, arguing girls reason more in terms of care and relationships.' },
      { heading: 'Lifespan Development', body: 'Erikson\'s 8 stages: each presents a psychosocial crisis that shapes personality. Key early stages: trust vs. mistrust (infancy), autonomy vs. shame (toddler), initiative vs. guilt (preschool), industry vs. inferiority (school age), identity vs. role confusion (adolescence).' },
    ],
    mustKnow: [
      'Piaget stages in order: Sensorimotor → Preoperational → Concrete Operational → Formal Operational.',
      'Conservation (understanding quantity doesn\'t change with shape) develops at concrete operational stage (~7 yrs).',
      'Egocentrism = can\'t take another\'s perspective (preoperational); NOT selfishness.',
      'ZPD = what a child can do with help but not alone; scaffolding bridges that gap.',
      'Secure attachment = caregiver responsive. Avoidant = caregiver unavailable. Anxious = caregiver inconsistent.',
      'Harlow: infant monkeys preferred cloth "mother" (comfort) over wire "mother" (food).',
      'Kohlberg Level 1 = self-interest. Level 2 = rules/laws. Level 3 = abstract principles.',
      'Critical period: there is an optimal time for certain developments (e.g., language acquisition).',
      'Theory of mind develops ~age 4; tested with false-belief tasks.',
      'Erikson Stage 5 = Identity vs. Role Confusion (adolescence).',
    ],
    mnemonics: [
      { label: 'Piaget Stages', text: '**"Silly People Can\'t Find Olivia"** → **S**ensorimotor → **P**reoperational → **C**oncrete → **F**ormal **O**perational.' },
      { label: 'Attachment Styles', text: '**"SAAD"** — **S**ecure, **A**voidant, **A**nxious/Ambivalent, **D**isorganized.' },
      { label: 'Kohlberg Levels', text: '**"Pre-Con-Post"** = **Pre**conventional (me), **Con**ventional (rules), **Post**conventional (principles).' },
      { label: 'ZPD vs Scaffolding', text: '**ZPD = the GAP. Scaffolding = the BRIDGE** over that gap.' },
      { label: 'Erikson Key Stage', text: '**"Teens need Identity"** → Stage 5 = Identity vs. Role Confusion = adolescence.' },
    ],
  },

  {
    id: 'kaplan-10',
    title: 'Motivation, Emotion, and Personality',
    keyTerms: [
      { term: 'Motivation', def: 'A need or desire that energizes and directs behavior toward a goal.' },
      { term: 'Drive-Reduction Theory', def: 'Hull: biological needs create drives; behavior is motivated to reduce these drives and restore homeostasis.' },
      { term: 'Homeostasis', def: 'The tendency to maintain a stable internal state (e.g., body temperature, blood sugar).' },
      { term: 'Instinct Theory', def: 'Behavior is motivated by innate biological instincts (McDougall); largely replaced by drive theory.' },
      { term: 'Arousal Theory', def: 'People are motivated to maintain an optimal level of arousal; not too high, not too low.' },
      { term: 'Incentive Theory', def: 'Behavior is pulled by external rewards (incentives) rather than pushed by internal drives.' },
      { term: 'Maslow\'s Hierarchy of Needs', def: 'Pyramid: physiological → safety → love/belonging → esteem → self-actualization. Lower needs must be met first.' },
      { term: 'Self-Actualization', def: 'Maslow: the drive to fulfill one\'s potential; the highest level of the hierarchy.' },
      { term: 'Intrinsic Motivation', def: 'Engaging in an activity for its own sake (interest, enjoyment) rather than for external reward.' },
      { term: 'Extrinsic Motivation', def: 'Engaging in an activity for external rewards (money, grades, praise).' },
      { term: 'Overjustification Effect', def: 'Providing extrinsic rewards for an already intrinsically motivating activity can reduce intrinsic motivation.' },
      { term: 'James-Lange Theory', def: 'We feel emotion as a result of noticing our physiological arousal (I\'m shaking → I must be afraid).' },
      { term: 'Cannon-Bard Theory', def: 'The physiological response and the subjective emotion occur simultaneously and independently.' },
      { term: 'Schachter-Singer Two-Factor Theory', def: 'Emotion = physiological arousal + cognitive label. We interpret the arousal using context.' },
      { term: 'Cognitive Appraisal Theory', def: 'Lazarus: the subjective meaning (appraisal) we assign to an event determines our emotional response.' },
      { term: 'Facial Feedback Hypothesis', def: 'Facial expressions can influence the emotions we feel (smiling can make you feel happier).' },
      { term: 'Universal Emotions', def: 'Ekman: six basic emotions recognized across cultures — happiness, sadness, fear, anger, disgust, surprise.' },
      { term: 'Psychoanalytic Theory', def: 'Freud: personality is shaped by unconscious conflicts, largely sexual and aggressive in nature.' },
      { term: 'Id', def: 'Freud: the primitive, unconscious reservoir of instinctual drives; operates on the pleasure principle.' },
      { term: 'Ego', def: 'Freud: the rational, conscious part; operates on the reality principle; mediates between id and superego.' },
      { term: 'Superego', def: 'Freud: the internalized moral standards and ideals; the "conscience."' },
      { term: 'Defense Mechanisms', def: 'Freud: unconscious strategies the ego uses to reduce anxiety by distorting reality.' },
      { term: 'Repression', def: 'Defense mechanism: blocking threatening thoughts from consciousness.' },
      { term: 'Projection', def: 'Attributing one\'s own unacceptable thoughts/feelings to others.' },
      { term: 'Rationalization', def: 'Creating logical-sounding justifications for unacceptable behaviors.' },
      { term: 'Regression', def: 'Returning to an earlier, more childlike behavior when under stress.' },
      { term: 'Displacement', def: 'Redirecting emotions toward a safer substitute target.' },
      { term: 'Reaction Formation', def: 'Expressing the opposite of one\'s true feelings.' },
      { term: 'Carl Rogers (Humanistic)', def: 'Person-centered theory; people have an innate drive toward growth (self-actualization); emphasized unconditional positive regard.' },
      { term: 'Self-Concept', def: 'Rogers: one\'s overall view of oneself; healthy development requires congruence between ideal self and actual self.' },
      { term: 'Unconditional Positive Regard', def: 'Rogers: accepting and valuing a person regardless of their behavior; essential for healthy development.' },
      { term: 'Big Five Personality Traits (OCEAN)', def: 'Openness, Conscientiousness, Extraversion, Agreeableness, Neuroticism. Research-supported, cross-culturally consistent traits.' },
      { term: 'Locus of Control', def: 'Rotter: the degree to which individuals believe they control their own fate (internal) vs. external forces (external).' },
    ],
    summary: [
      { heading: 'Theories of Motivation', body: 'Drive-reduction: internal needs push behavior (homeostasis). Incentive: external rewards pull behavior. Arousal: optimal stimulation level. Maslow\'s hierarchy: prioritize basic needs before higher ones. Intrinsic motivation is more durable; extrinsic rewards can undermine intrinsic interest (overjustification effect).' },
      { heading: 'Emotion Theories', body: 'James-Lange: body first, emotion second. Cannon-Bard: simultaneous. Schachter-Singer: arousal + label = emotion (misattribution possible). Cognitive appraisal (Lazarus): meaning we assign determines emotion. Ekman: 6 universal emotions (facial expressions cross-cultural).' },
      { heading: 'Freudian Personality', body: 'Personality = id (pleasure) + ego (reality) + superego (morality). Unconscious conflicts → anxiety → defense mechanisms. Psychosexual stages (oral, anal, phallic, latency, genital) — fixation at a stage causes adult personality issues. Projective tests (Rorschach, TAT) claim to access the unconscious.' },
      { heading: 'Humanistic Personality', body: 'Rogers: unconditional positive regard, self-concept, congruence. Maslow: hierarchy capped by self-actualization. Humanistic theories are optimistic but criticized for being unmeasurable.' },
      { heading: 'Trait Theories', body: 'Traits are stable, cross-situational dispositions. Big Five (OCEAN) is the most empirically supported framework. Locus of control: internal locus → better health and achievement outcomes. Personality has both genetic (heritability ~50%) and environmental components.' },
    ],
    mustKnow: [
      'Maslow\'s hierarchy (bottom to top): Physiological → Safety → Love → Esteem → Self-actualization.',
      'Overjustification effect: external rewards reduce intrinsic motivation.',
      'James-Lange: "I see a bear → I run → I feel fear." Cannon-Bard: running and fear happen simultaneously.',
      'Schachter-Singer two-factor: arousal + cognitive label = emotion.',
      'Freud\'s id = pleasure principle; ego = reality principle; superego = morality.',
      'Key defense mechanisms: repression, projection, rationalization, regression, displacement.',
      'Rogers: unconditional positive regard is essential for healthy self-concept.',
      'Big Five OCEAN: Openness, Conscientiousness, Extraversion, Agreeableness, Neuroticism.',
      'Internal locus of control = belief you control your fate; linked to better outcomes.',
      'Ekman: 6 basic emotions are universal and cross-cultural.',
    ],
    mnemonics: [
      { label: 'Maslow\'s Hierarchy', text: '**"Please Stop Loving Every Self"** → **P**hysiological, **S**afety, **L**ove, **E**steem, **S**elf-actualization.' },
      { label: 'Big Five OCEAN', text: '**OCEAN** — **O**penness, **C**onscientiousness, **E**xtraversion, **A**greeableness, **N**euroticism.' },
      { label: 'Emotion Theories Order', text: '**J-L → C-B → S-S** = **J**ames-**L**ange (body first), **C**annon-**B**ard (simultaneous), **S**chachter-**S**inger (arousal + label).' },
      { label: 'Freud\'s Structure', text: '**I = instincts (Id), E = executive (Ego), S = should (Superego)**.' },
      { label: 'Defense Mechanisms', text: '**"RRRPDR"** — **R**epression, **R**egression, **R**ationalization, **P**rojection, **D**isplacement, **R**eaction Formation.' },
    ],
  },

  {
    id: 'kaplan-11',
    title: 'Clinical Psychology',
    keyTerms: [
      { term: 'Psychological Disorder', def: 'A pattern of behavior or mental processes that causes significant distress or impairment, and is not culturally expected.' },
      { term: 'DSM-5', def: 'Diagnostic and Statistical Manual of Mental Disorders, 5th edition; the primary diagnostic reference used in the U.S.' },
      { term: 'Major Depressive Disorder (MDD)', def: 'Persistent depressed mood or loss of interest for ≥2 weeks, plus 4+ other symptoms (sleep, appetite, concentration changes, etc.).' },
      { term: 'Bipolar Disorder', def: 'Episodes of depression alternating with mania (elevated/irritable mood, grandiosity, decreased need for sleep).' },
      { term: 'Generalized Anxiety Disorder (GAD)', def: 'Excessive, uncontrollable worry about multiple areas of life lasting ≥6 months.' },
      { term: 'Panic Disorder', def: 'Recurrent, unexpected panic attacks plus persistent concern about future attacks.' },
      { term: 'Specific Phobia', def: 'Marked, disproportionate fear of a specific object or situation; person recognizes it as irrational.' },
      { term: 'Social Anxiety Disorder', def: 'Intense fear of social situations involving potential scrutiny or embarrassment.' },
      { term: 'OCD', def: 'Obsessive-Compulsive Disorder: intrusive, unwanted obsessions (thoughts) + compulsions (repetitive behaviors to reduce anxiety).' },
      { term: 'PTSD', def: 'Post-Traumatic Stress Disorder: exposure to traumatic event → flashbacks, avoidance, hyperarousal, negative cognitions/mood.' },
      { term: 'Schizophrenia', def: 'Psychotic disorder: positive symptoms (hallucinations, delusions, disorganized speech) + negative symptoms (flat affect, avolition, alogia).' },
      { term: 'Positive Symptoms (Schizophrenia)', def: 'Symptoms added to normal experience: hallucinations (false perceptions) and delusions (false beliefs).' },
      { term: 'Negative Symptoms (Schizophrenia)', def: 'Diminished normal function: flat affect, poverty of speech (alogia), lack of motivation (avolition), anhedonia.' },
      { term: 'Dopamine Hypothesis', def: 'Schizophrenia is associated with excess dopamine activity; antipsychotics block dopamine D2 receptors.' },
      { term: 'Narcissistic Personality Disorder', def: 'Pervasive grandiosity, need for admiration, and lack of empathy; one of the Cluster B ("dramatic") PDs.' },
      { term: 'Borderline Personality Disorder', def: 'Cluster B: unstable relationships, identity, and mood; self-harm; intense fear of abandonment.' },
      { term: 'Antisocial Personality Disorder', def: 'Cluster B: persistent disregard for others\' rights; deceitfulness, impulsivity, lack of remorse.' },
      { term: 'Cognitive-Behavioral Therapy (CBT)', def: 'Combines cognitive therapy (changing distorted thoughts) with behavioral techniques; evidence-based for depression, anxiety, and more.' },
      { term: 'Systematic Desensitization', def: 'Wolpe: behavioral therapy for phobias; pair relaxation with gradual exposure to feared stimulus hierarchy.' },
      { term: 'Exposure and Response Prevention', def: 'First-line behavioral treatment for OCD: expose to fear trigger while preventing compulsive response.' },
      { term: 'Psychoanalytic/Psychodynamic Therapy', def: 'Based on Freud; explores unconscious conflicts; techniques include free association and dream analysis.' },
      { term: 'Client-Centered Therapy', def: 'Carl Rogers: non-directive therapy emphasizing empathy, unconditional positive regard, and genuineness to promote self-actualization.' },
      { term: 'SSRIs', def: 'Selective Serotonin Reuptake Inhibitors; first-line medication for depression and anxiety; block serotonin reuptake.' },
      { term: 'Lithium', def: 'Mood stabilizer used for bipolar disorder; first FDA-approved treatment for mania.' },
      { term: 'Antipsychotics', def: 'Medications for schizophrenia; typical antipsychotics block D2 dopamine receptors.' },
      { term: 'ECT', def: 'Electroconvulsive Therapy: brief electrical stimulation to induce seizure; used for severe, treatment-resistant depression.' },
      { term: 'Medical Model', def: 'Views psychological disorders as diseases with biological causes that can be diagnosed and treated medically.' },
      { term: 'Diathesis-Stress Model', def: 'Disorders arise from an interaction between a genetic vulnerability (diathesis) and environmental stressors.' },
    ],
    summary: [
      { heading: 'Mood Disorders', body: 'MDD: 2+ weeks of depressed mood/anhedonia + symptoms. Bipolar: cycles of depression and mania. Both have strong genetic components and respond to medication (SSRIs for depression; lithium for bipolar) and psychotherapy (CBT).' },
      { heading: 'Anxiety Disorders', body: 'GAD, panic disorder, phobias, social anxiety, OCD, and PTSD all involve excessive fear or anxiety. Best treatments: CBT + exposure-based therapy. SSRIs are first-line pharmacotherapy. OCD = exposure and response prevention (ERP).' },
      { heading: 'Schizophrenia', body: 'Positive symptoms: hallucinations, delusions (add to experience). Negative symptoms: flat affect, avolition (remove from normal function). Dopamine excess is implicated; treated with antipsychotics. Stress-diathesis model: genetic vulnerability + environmental triggers.' },
      { heading: 'Personality Disorders', body: 'Cluster A (odd/eccentric): paranoid, schizoid, schizotypal. Cluster B (dramatic/emotional): antisocial, borderline, narcissistic, histrionic. Cluster C (anxious/fearful): avoidant, dependent, OCD. Personality disorders are ego-syntonic (feel normal to the person).' },
      { heading: 'Psychotherapies', body: 'Psychodynamic: unconscious, free association. CBT: challenge distorted cognitions. Humanistic (Rogers): unconditional positive regard, client-led. Behavioral: exposure, systematic desensitization. DBT (for BPD): combines CBT with mindfulness and distress tolerance.' },
    ],
    mustKnow: [
      'MDD criteria: ≥2 weeks depressed mood or anhedonia + 4 other symptoms.',
      'Bipolar disorder: mania episodes + depression episodes; treated with mood stabilizers (lithium).',
      'Schizophrenia positive symptoms = hallucinations + delusions; negative = flat affect + avolition.',
      'Dopamine excess → schizophrenia. Serotonin deficit → depression.',
      'CBT is evidence-based for depression, anxiety, and OCD.',
      'Systematic desensitization: relaxation + hierarchy of feared stimuli (classical conditioning).',
      'Rogers\' client-centered therapy: empathy, unconditional positive regard, congruence.',
      'SSRIs block serotonin reuptake → treat depression and anxiety.',
      'Narcissistic PD = grandiosity + lack of empathy (Cluster B).',
      'Diathesis-stress: genetic vulnerability + environmental stress → disorder.',
    ],
    mnemonics: [
      { label: 'Cluster B PDs', text: '**"Bad Boys Are Nasty Histrionics"** → **B**orderline, **A**ntisocial, **N**arcissistic, **H**istrionic.' },
      { label: 'Schizophrenia Symptoms', text: '**"Positive ADDS, Negative TAKES AWAY"** — hallucinations/delusions are added experiences; flat affect/avolition take away normal function.' },
      { label: 'MDD Mnemonic', text: '**SIG E CAPS** — Sleep, Interest, Guilt, Energy, Concentration, Appetite, Psychomotor, Suicide (8 criteria; need 5+ including depressed mood or anhedonia).' },
      { label: 'Therapy Types', text: '**P-C-H-B** — **P**sychodynamic (unconscious), **C**BT (thoughts + behavior), **H**umanistic (growth), **B**ehavioral (conditioning).' },
      { label: 'Lithium', text: '**"Lithium = Level out"** — mood stabilizer that levels out the highs and lows of bipolar disorder.' },
    ],
  },

  {
    id: 'kaplan-12',
    title: 'Social Psychology',
    keyTerms: [
      { term: 'Attribution Theory', def: 'How we explain behavior — either to internal (dispositional) or external (situational) causes.' },
      { term: 'Fundamental Attribution Error (FAE)', def: 'Tendency to overestimate dispositional causes and underestimate situational causes when explaining others\' behavior.' },
      { term: 'Actor-Observer Bias', def: 'We attribute our own behavior to situations (actor) but others\' to their character (observer).' },
      { term: 'Self-Serving Bias', def: 'Attributing successes to internal factors and failures to external ones.' },
      { term: 'Cognitive Dissonance', def: 'Festinger: discomfort from holding inconsistent cognitions; reduces discomfort by changing beliefs or behavior.' },
      { term: 'Attitude Change', def: 'Persuasion via central route (thoughtful argument) or peripheral route (superficial cues like attractiveness).' },
      { term: 'Conformity', def: 'Adjusting behavior or beliefs to match group norms.' },
      { term: 'Asch Conformity Experiment', def: 'Demonstrated that people conform to obviously wrong group answers due to normative social influence.' },
      { term: 'Normative Social Influence', def: 'Conforming to fit in and be liked; involves public compliance without private acceptance.' },
      { term: 'Informational Social Influence', def: 'Conforming because we believe the group has accurate information; involves genuine attitude change.' },
      { term: 'Obedience', def: 'Following direct orders from an authority figure; studied by Milgram.' },
      { term: 'Milgram Experiment', def: 'Participants administered apparent electric shocks to a "victim" on authority\'s orders; ~65% went to maximum voltage; showed power of obedience.' },
      { term: 'Social Facilitation', def: 'Performance of simple/well-learned tasks improves in the presence of others; complex/novel tasks worsen.' },
      { term: 'Social Loafing', def: 'People exert less effort when working in a group than when working alone (diffusion of responsibility).' },
      { term: 'Deindividuation', def: 'Loss of self-awareness and restraint in a group or crowd; can lead to antisocial behavior.' },
      { term: 'Groupthink', def: 'Janis: cohesive groups prioritize consensus over critical thinking, leading to poor decisions.' },
      { term: 'Group Polarization', def: 'Group discussion tends to intensify the initial opinions held by group members.' },
      { term: 'Bystander Effect', def: 'Darley & Latané: individuals are less likely to help in an emergency when others are present.' },
      { term: 'Diffusion of Responsibility', def: 'Mechanism behind bystander effect: each person assumes someone else will help.' },
      { term: 'Altruism', def: 'Helping others with no expectation of personal benefit.' },
      { term: 'Foot-in-the-Door Technique', def: 'Compliance tactic: start with a small request, then make a larger request; works by self-perception consistency.' },
      { term: 'Door-in-the-Face Technique', def: 'Compliance tactic: start with a large request (likely refused), then make a smaller, more reasonable request.' },
      { term: 'Stereotypes', def: 'Oversimplified generalizations about a group; cognitive schemas about social groups.' },
      { term: 'Prejudice', def: 'Unjustified negative attitude toward a group based on group membership; an emotional response.' },
      { term: 'Discrimination', def: 'Unjustified negative behavior directed toward a group member.' },
      { term: 'In-Group Bias', def: 'Tendency to favor members of one\'s own group over out-group members.' },
      { term: 'Scapegoating', def: 'Blaming an out-group member for one\'s own problems or group frustrations.' },
      { term: 'Just-World Phenomenon', def: 'Belief that people get what they deserve; can lead to blaming victims.' },
      { term: 'Social Comparison Theory', def: 'Festinger: we evaluate our opinions and abilities by comparing ourselves to others.' },
      { term: 'Mere Exposure Effect', def: 'Zajonc: repeated exposure to a stimulus increases liking for it.' },
      { term: 'Reciprocity Norm', def: 'Social obligation to return favors; basis for door-in-the-face technique.' },
    ],
    summary: [
      { heading: 'Attribution & Bias', body: 'We explain behavior by attributing it to internal traits (dispositional) or situations. FAE: we over-attribute others\' behavior to personality. Self-serving bias: we take credit for success, blame situations for failure. Actor-observer: we see others as acting from character, ourselves as responding to situations.' },
      { heading: 'Conformity & Obedience', body: 'Asch: people conform to wrong group answers (normative influence). Milgram: ~65% delivered maximum "shocks" under authority pressure. Situational factors (anonymity, distance from victim, authority presence) are more powerful than expected.' },
      { heading: 'Group Dynamics', body: 'Social facilitation: audience boosts simple task performance. Social loafing: group reduces individual effort. Deindividuation: loss of self in crowds → antisocial behavior. Groupthink: cohesion crushes dissent. Group polarization: discussion amplifies initial views.' },
      { heading: 'Helping Behavior', body: 'Bystander effect: more witnesses → less likely any one person helps (diffusion of responsibility). To increase helping: create a sense of personal responsibility. Altruism can be explained by kin selection, reciprocal altruism, or social norms.' },
      { heading: 'Prejudice & Persuasion', body: 'Stereotypes (cognitive) → prejudice (affective) → discrimination (behavioral). In-group bias and scapegoating sustain prejudice. Foot-in-the-door: small → large request. Door-in-the-face: large (refused) → small request. Cognitive dissonance motivates attitude change after behavior.' },
    ],
    mustKnow: [
      'FAE: overestimate personality, underestimate situation when judging OTHERS.',
      'Self-serving bias: success = me. Failure = the situation.',
      'Milgram: 65% complied to maximum shock; showed power of authority and obedience.',
      'Asch conformity: majority effect, even when clearly wrong (normative influence).',
      'Bystander effect: more bystanders → less likely to help (diffusion of responsibility).',
      'Social facilitation: simple tasks improve with audience; complex tasks get worse.',
      'Social loafing: less effort in groups. Deindividuation: lost identity in crowds.',
      'Foot-in-the-door: small then large request. Door-in-the-face: large then small request.',
      'Groupthink: cohesion > critical thinking → poor decisions.',
      'Cognitive dissonance: inconsistent cognitions → change attitude to reduce discomfort.',
    ],
    mnemonics: [
      { label: 'FAE', text: '**"We blame THEM on personality, we blame US on situations."** The FAE applies to judging OTHERS, not ourselves.' },
      { label: 'Bystander Effect', text: '**"More people, less help"** — diffusion of responsibility. To break: single someone out by name.' },
      { label: 'Compliance Techniques', text: '**Foot = small first** (foot in the door). **Door = big first** (door in the face, then retreat).' },
      { label: 'Social Facilitation vs Loafing', text: '**Facilitation = performing FOR an audience** (simple tasks better). **Loafing = performing WITH a group** (less effort).' },
      { label: 'Groupthink Signs', text: '**"CCCS"** — **C**ohesion, **C**ensorship (of dissent), **C**onfidence (illusion of invulnerability), **S**tereotyping out-groups.' },
    ],
  },
];
