// Per-chapter content extensions for the study notes.
// Each entry adds GATE-XH-C5-focused depth on top of STUDY_DATA:
//   extendedTerms — additional concepts Kaplan's AP book doesn't cover but GATE tests
//   gateFocus     — exam-specific angles (researchers, numbers, comparisons)
//   pitfalls      — classic confusions that generate wrong answers
export const STUDY_EXTENSIONS = {
  'kaplan-4': {
    extendedTerms: [
      { term: 'Double-Blind Procedure', def: 'Both participants and experimenters are unaware of group assignments; controls placebo effects AND experimenter bias simultaneously.' },
      { term: 'Third Variable Problem', def: 'An unmeasured variable (e.g., age) may cause both correlated variables, creating a spurious correlation.' },
      { term: 'Operational Definition', def: 'Exact statement of how a variable is measured or manipulated (e.g., "stress = cortisol level in nmol/L").' },
      { term: 'Sampling Bias', def: 'Sample not representative of population; most common form is convenience sampling of college students (WEIRD samples).' },
      { term: 'Descriptive vs Inferential Statistics', def: 'Descriptive summarize data (mean, SD); inferential test hypotheses (t-tests, ANOVA, p-values, significance).' },
      { term: 'Effect Size', def: 'Magnitude of a finding independent of sample size (Cohen\u2019s d, r). A result can be significant yet tiny in effect.' },
      { term: 'Reliability', def: 'Consistency of measurement: test-retest (over time), inter-rater (across observers), internal consistency.' },
      { term: 'Validity', def: 'Accuracy of measurement: construct (measures the concept), content (covers the domain), criterion/predictive (predicts outcomes).' },
      { term: 'Demand Characteristics', def: 'Participants guess the hypothesis and alter behavior; controlled by deception, filler tasks, double-blind designs.' },
      { term: 'IRB / Ethics Committee', def: 'Reviews research proposals to ensure participant safety before any data collection begins.' },
      { term: 'Skewed Distributions', def: 'Positive skew: tail to the right (mean > median). Negative skew: tail to the left (mean < median).' },
      { term: 'Scatterplot & Direction', def: 'Visual display of correlation; cloud sloping up = positive r, down = negative r, random = near zero.' },
    ],
    gateFocus: [
      'GATE loves the "which method establishes causality" question \u2014 answer is always a true experiment with random assignment.',
      'Be ready to compute/compare mean vs median from a small dataset with one outlier.',
      'Know the difference between null hypothesis (no effect) and alternative hypothesis.',
      'Ethics questions hinge on order: consent BEFORE study, debrief AFTER (especially if deception was used).',
      'r = 0 does NOT mean no relationship \u2014 it means no LINEAR relationship.',
    ],
    pitfalls: [
      'Confusing random sampling (who is in the study) with random assignment (which condition they get).',
      'Reading a scatterplot with an outlier as "strong" correlation \u2014 always check whether r is driven by outliers.',
      '"Statistically significant" \u2260 "important" \u2014 check effect size.',
      'Assuming a low p-value proves the hypothesis true; it only indicates results are unlikely under the null.',
    ],
  },

  'kaplan-5': {
    extendedTerms: [
      { term: 'Resting Potential (\u221270 mV)', def: 'Polarized state of a neuron at rest, maintained by sodium-potassium pumps (3 Na\u207A out, 2 K\u207A in).' },
      { term: 'All-or-Nothing Principle', def: 'A neuron fires at full strength or not at all; intensity of stimulation is coded by firing RATE, not amplitude.' },
      { term: 'Refractory Period', def: 'Brief period after firing when a neuron cannot fire again; limits maximum firing rate.' },
      { term: 'Agonist', def: 'Drug/chemical that MIMICS or enhances a neurotransmitter\u2019s effect (e.g., nicotine mimics ACh).' },
      { term: 'Antagonist', def: 'Blocks or inhibits a neurotransmitter\u2019s effect (e.g., curare blocks ACh receptors).' },
      { term: 'Medulla', def: 'Hindbrain structure controlling heartbeat, breathing, blood pressure; damage is fatal.' },
      { term: 'Reticular Formation', def: 'Net of neurons through the brainstem controlling arousal and attention; lesion \u2192 coma.' },
      { term: 'Limbic System', def: 'Collective term: hippocampus + amygdala + hypothalamus (+ cingulate cortex). Emotion and memory circuit.' },
      { term: 'Motor Cortex', def: 'Strip at the rear of frontal lobe issuing voluntary movement commands; body parts mapped by size of use.' },
      { term: 'Somatosensory Cortex', def: 'Strip at front of parietal lobe registering touch across the body; adjacent to motor cortex.' },
      { term: 'Plasticity', def: 'Brain\u2019s ability to reorganize after damage, especially young brains; phantom limb shows remapping.' },
      { term: 'Split-Brain Patients', def: 'Corpus callosum severed; each hemisphere processes information independently \u2014 object in LEFT visual field \u2192 processed by RIGHT hemisphere \u2192 cannot name it (speech is left-lateralized).' },
      { term: 'Lesion Method', def: 'Studying behavior after deliberate or natural brain damage; established localization before imaging existed.' },
      { term: 'TMS', def: 'Transcranial magnetic stimulation; temporarily disrupts activity in a cortical region to test its causal role.' },
      { term: 'Adrenal Glands', def: 'Release epinephrine/adrenaline, norepinephrine, and cortisol during stress.' },
      { term: 'Oxytocin', def: 'Hormone linked to bonding, trust, and social recognition; released during childbirth and nursing.' },
    ],
    gateFocus: [
      'Trace the pathway: stimulus \u2192 receptor \u2192 afferent neuron \u2192 CNS \u2192 efferent neuron \u2192 muscle/gland.',
      'Know hemisphere lateralization: left = language/logic/sequential; right = spatial/faces/emotional tone. Speech almost always left.',
      'Numbers worth memorizing: resting potential \u221270 mV; ~65% split-brain facts appear repeatedly in XH papers.',
      'fMRI = WHERE activity happens (spatial); EEG = WHEN (temporal); lesion/TMS give causal evidence.',
      'Match neurotransmitter \u2192 disorder pairs quickly: ACh\u2013Alzheimer, dopamine\u2013schizophrenia/Parkinson, serotonin\u2013depression, GABA\u2013anxiety/epilepsy, endorphins\u2013pain.',
    ],
    pitfalls: [
      'Sympathetic vs parasympathetic reversed on quick reads \u2014 sympathetic ACCELERATES heart, constricts vessels.',
      'Thalamus relays all senses EXCEPT smell (olfaction goes straight to cortex).',
      'Hippocampus forms NEW memories but old memories are stored across cortex (HM could recall childhood but not form new memories).',
      'Broca (production, frontal) vs Wernicke (comprehension, temporal) \u2014 swapped constantly under exam pressure.',
    ],
  },

  'kaplan-6': {
    extendedTerms: [
      { term: 'Wavelength', def: 'Physical property of light determining HUE/color; amplitude determines brightness.' },
      { term: 'Amplitude (sound)', def: 'Physical property of sound waves determining LOUDNESS (decibels); frequency determines pitch (hertz).' },
      { term: 'Conduction vs Sensorineural Deafness', def: 'Conduction: mechanical problem in middle ear (hearing aids help). Sensorineural: hair cell/nerve damage (cochlear implants help).' },
      { term: 'Gate-Control Theory of Pain', def: 'Spinal "gate": competing touch signals can close the gate on pain signals \u2014 why rubbing a bump helps.' },
      { term: 'Retinal Disparity', def: 'Binocular cue: slightly different images in two eyes; larger disparity = closer object.' },
      { term: 'Convergence', def: 'Binocular cue: eyes turn inward more for close objects; brain senses muscle strain.' },
      { term: 'Linear Perspective', def: 'Monocular cue: parallel lines converge with distance (railroad tracks).' },
      { term: 'Perceptual Constancy', def: 'Perceiving objects as stable (size, shape, color) despite changing retinal images.' },
      { term: 'Phi Phenomenon / Stroboscopic Movement', def: 'Apparent motion from sequential static images \u2014 basis of film and animation.' },
      { term: 'McGurk Effect', def: 'Audio-visual integration: seeing lips say "ga" while hearing "ba" produces perception of "da" \u2014 top-down influence.' },
      { term: 'Cocktail Party Effect', def: 'Ability to focus attention on one conversation while filtering others; own name still penetrates.' },
      { term: 'Inattentional Blindness', def: 'Failure to perceive visible stimuli when attention is elsewhere (invisible gorilla study).' },
      { term: 'Subliminal Perception', def: 'Processing below conscious awareness; measurable priming exists, but no evidence for subliminal self-help messages changing complex behavior.' },
      { term: 'Ponzo / M\u00fcller-Lyer Illusions', def: 'Depth cues misapplied to 2D figures produce systematic size distortions \u2014 evidence for constructive perception.' },
    ],
    gateFocus: [
      'Signal detection matrix: hit, miss, false alarm, correct rejection \u2014 be able to classify outcomes given response bias changes.',
      'Weber\u2019s law is about PROPORTION (k = \u0394I/I), not absolute amounts.',
      'Rods vs cones table: rods \u2014 periphery, dim light, no color, many-to-one convergence; cones \u2014 fovea, bright light, color, one-to-one.',
      'Trichromatic explains color mixing at the RETINA; opponent-process explains afterimages at later neural stages \u2014 both are true at different levels.',
      'Place theory covers high pitches, frequency theory low pitches (<500 Hz), volley principle middle range.',
    ],
    pitfalls: [
      'Absolute threshold is defined at 50% detection rate \u2014 not "ever detectable".',
      'Adaptation applies to CONSTANT stimuli; it does not explain why you see afterimages (that\u2019s opponent-process fatigue).',
      'Bottom-up = raw sensory data driven; top-down = expectation driven. Illusions are usually top-down failures.',
      'Interposition = one object OCCLUDES another (the occluding one is nearer), often confused with relative size.',
    ],
  },

  'kaplan-7': {
    extendedTerms: [
      { term: 'Higher-Order Conditioning', def: 'A well-established CS can itself act as a UCS to condition a new neutral stimulus (bell \u2192 light \u2192 salivation).' },
      { term: 'Taste Aversion (Garcia Effect)', def: 'One-trial conditioning of nausea to food/flavor even hours later; violates normal contiguity rules; biological preparedness.' },
      { term: 'Biological Preparedness', def: 'Organisms are evolutionarily primed to associate certain stimuli (taste, snakes) with certain outcomes more easily than others.' },
      { term: 'Rescorla-Wagner Model', def: 'Conditioning depends on EXPECTATION and surprise; CS predicts UCS \u2014 blocking occurs when new CS adds no predictive value.' },
      { term: 'Blocking', def: 'Failure to condition to a second CS when the first already predicts the UCS.' },
      { term: 'Premack Principle', def: 'Preferred activity can reinforce a less-preferred one ("eat vegetables, then dessert").' },
      { term: 'Instinctive Drift', def: 'Breland: trained behaviors drift back toward instinctual patterns regardless of reinforcement.' },
      { term: 'Overjustification Effect', def: 'External reward for intrinsically enjoyable behavior reduces later intrinsic motivation (Lepper marker study).' },
      { term: 'Behavior Modification / Token Economy', def: 'Applied operant conditioning: tokens earned for target behaviors, exchanged for rewards; used in institutions.' },
      { term: 'Mirror Neurons', def: 'Fire when performing AND observing an action; proposed neural basis for imitation and observational learning.' },
      { term: 'Preparedness in Phobias', def: 'Phobias concentrate on evolutionarily threats (snakes, heights, dark) rather than modern dangers (outlets, cars).' },
    ],
    gateFocus: [
      'Classify any scenario fast: does consequence ADD something pleasant/unpleasant or REMOVE something? Increase or decrease behavior?',
      'Negative reinforcement appears in nearly every paper \u2014 removing aversive \u2192 INCREASES behavior (aspirin example).',
      'Reinforcement schedules ranked by extinction resistance: VR > VI > FR > FI.',
      'Classical vs operant decision rule: behavior ELICITED by preceding stimulus (classical) vs EMITTED and changed by consequences (operant).',
      'Know the researchers cold: Pavlov, Watson (Little Albert), Skinner, Thorndike (law of effect), Bandura, Tolman, K\u00f6hler, Seligman, Garcia, Breland.',
    ],
    pitfalls: [
      'Little Albert was CLASSICAL conditioning (fear conditioned to rat), not operant.',
      'Punishment decreases behavior; negative reinforcement increases it \u2014 "negative" means removal, not bad outcome.',
      'Extinction in classical = CS without UCS; in operant = response without reinforcement. Different procedures, same name.',
      'Shaping is operant (successive approximations), NOT how classical associations form.',
    ],
  },

  'kaplan-8': {
    extendedTerms: [
      { term: 'Atkinson-Shiffrin Model', def: 'Three-box memory model: sensory register \u2192 short-term store \u2192 long-term store, gated by attention and rehearsal.' },
      { term: 'Levels of Processing (Craik & Lockhart)', def: 'Semantic/deep processing beats structural/shallow processing for retention, regardless of intention to learn.' },
      { term: 'Testing Effect', def: 'Actively retrieving information strengthens memory more than restudying \u2014 the research basis for flashcards and practice testing.' },
      { term: 'Encoding Specificity', def: 'Recall is best when retrieval context matches encoding context (scuba divers studied on land recalled better underwater).' },
      { term: 'State-Dependent Memory', def: 'Better recall when in the same physiological/psychological state as at encoding.' },
      { term: 'Mnemonics & Method of Loci', def: 'Imagery-based organization techniques that exploit deep processing and spatial memory.' },
      { term: 'Anterograde Amnesia', def: 'Cannot form NEW memories after damage (patient HM, hippocampus removed); implicit learning survives.' },
      { term: 'Retrograde Amnesia', def: 'Loss of memories formed BEFORE the injury; recent memories most vulnerable.' },
      { term: 'Alzheimer\u2019s Disease', def: 'Progressive memory disorder; ACh depletion, plaques and tangles; hippocampus affected early.' },
      { term: 'Framing Effect', def: 'Decisions change based on how options are worded ("90% survival" vs "10% mortality").' },
      { term: 'Anchoring Effect', def: 'Over-reliance on initial value when estimating; first number seen biases subsequent judgments.' },
      { term: 'Sunk Cost Fallacy', def: 'Continuing an endeavor because of prior investment despite negative expected value.' },
      { term: 'Belief Perseverance', def: 'Beliefs persist even after their supporting evidence is discredited.' },
      { term: 'Mental Set', def: 'Using previously successful strategies even when better ones exist.' },
      { term: 'Convergent vs Divergent Thinking', def: 'Convergent narrows to one correct answer; divergent generates many possibilities (creativity measure).' },
      { term: 'Phoneme & Morpheme', def: 'Smallest sound unit (~44 in English) vs smallest meaning unit; language hierarchy: phonemes \u2192 morphemes \u2192 words \u2192 phrases.' },
      { term: 'Language Acquisition Device', def: 'Chomsky: innate universal grammar mechanism; supported by poverty-of-the-stimulus argument.' },
      { term: 'Washoe / Koko / Kanzi', def: 'Ape language studies: sign-language vocabularies and symbol use; debate over true syntax vs learned association.' },
      { term: 'Linguistic Relativity', def: 'Whorf: language shapes thought; strong version rejected, weak version supported by color-perception studies.' },
    ],
    gateFocus: [
      'Memory question flowchart: failure at encoding, storage (decay), or retrieval (interference/cue absence)? Match symptom to stage.',
      'Proactive = OLD \u2192 new. Retroactive = NEW \u2192 old. Test: which direction does the interfering material come FROM.',
      'Serial position curve: primacy = LTM (rehearsed), recency = STM (still active). Delayed recall kills recency only.',
      'HM case: hippocampus removal \u2192 anterograde amnesia with intact procedural learning \u2014 proof of multiple memory systems.',
      'Heuristic identification practice: availability = ease of examples; representativeness = prototype match; anchoring = starting point.',
    ],
    pitfalls: [
      'Working memory is not just "bigger STM" \u2014 it actively MANIPULATES information (Baddeley: central executive, phonological loop, visuospatial sketchpad).',
      'Recognition > cued recall > free recall \u2014 multiple-choice tests benefit from recognition strength.',
      'Misinformation effect shows memory is RECONSTRUCTIVE; Loftus\u2019 "smashed" vs "hit" verb manipulation changes speed estimates.',
      'Fluid intelligence declines with age but crystallized keeps growing \u2014 don\u2019t swap them.',
    ],
  },

  'kaplan-9': {
    extendedTerms: [
      { term: 'Cross-Sectional vs Longitudinal Design', def: 'Cross-sectional compares ages at one time (cohort effects risk); longitudinal follows same people over years (attrition risk).' },
      { term: 'Cohort Effect', def: 'Differences between age groups due to shared generational experience, not development itself.' },
      { term: 'Teratogens', def: 'Harmful agents (alcohol, rubella, nicotine) crossing the placenta and damaging prenatal development; effects worst during critical periods.' },
      { term: 'Fetal Alcohol Syndrome', def: 'Leading preventable cause of intellectual disability; facial abnormalities, cognitive deficits.' },
      { term: 'Rooting & Sucking Reflexes', def: 'Newborn reflexes indicating neurological health; rooting = turn toward cheek touch, seeking nipple.' },
      { term: 'Habituation Paradigm', def: 'Infant cognition method: decreased looking at repeated stimulus reveals discrimination and preference.' },
      { term: 'Baillargeon\u2019s Violation-of-Expectation', def: 'Infants look longer at impossible events \u2014 suggests object permanence earlier than Piaget claimed.' },
      { term: 'Vygotsky vs Piaget', def: 'Vygotsky emphasized social interaction, language, and culture driving development; Piaget emphasized individual exploration.' },
      { term: 'Parenting Styles (Baumrind)', def: 'Authoritative (warm+demanding) \u2192 best outcomes; authoritarian (cold+demanding); permissive (warm+undemanding); neglectful (neither).' },
      { term: 'Contact Comfort', def: 'Harlow: infant monkeys chose cloth surrogate over wire milk-giver \u2014 attachment is about comfort, not feeding.' },
      { term: 'Strange Situation', def: 'Ainsworth\u2019s separation-reunion procedure classifying secure / avoidant / resistant / disorganized attachment.' },
      { term: 'Erikson\u2019s Psychosocial Stages', def: 'Eight lifelong crises: trust, autonomy, initiative, industry, identity, intimacy, generativity, integrity.' },
      { term: 'Intimacy vs Isolation', def: 'Young adulthood crisis (Erikson stage 6): forming committed relationships.' },
      { term: 'Generativity vs Stagnation', def: 'Middle adulthood: contributing to next generation vs self-absorption.' },
      { term: 'K\u00fcbler-Ross Stages of Dying', def: 'Denial, anger, bargaining, depression, acceptance \u2014 descriptive, not strictly sequential.' },
      { term: 'Gender Schema Theory', def: 'Children organize gender knowledge into schemas that guide behavior; combines social learning with cognition.' },
    ],
    gateFocus: [
      'Piaget\u2019s stages matched to tasks: object permanence (sensorimotor), conservation + egocentrism (preoperational fails both), classification (concrete), hypothetical deduction (formal).',
      'Attachment style \u2192 caregiver pattern mapping is a recurring item: consistent/responsive \u2192 secure; unavailable \u2192 avoidant; inconsistent \u2192 resistant; frightening \u2192 disorganized.',
      'Kohlberg\u2019s stages tested via moral dilemmas (Heinz); note Gilligan\u2019s care-orientation critique.',
      'Nature-nurture items favor INTERACTIONIST answers (diathesis-stress, epigenetics) over either extreme.',
      'Know the classic studies by name: Harlow (contact comfort), Ainsworth (strange situation), Lorenz (imprinting), Piaget (three mountains, conservation), Baillargeon (drawbridge).',
    ],
    pitfalls: [
      'Egocentrism is a COGNITIVE limitation, not selfishness \u2014 preoperational children literally cannot take other perspectives.',
      'Object permanence age: Piaget said ~8 months; Baillargeon\u2019s methods suggest much earlier. Know both positions.',
      'Longitudinal design\u2019s main weakness is ATTRITION (dropouts), cross-sectional\u2019s is COHORT effects.',
      'Adolescence risk-taking is linked to immature prefrontal cortex with matured reward circuits \u2014 not "hormones alone".',
    ],
  },

  'kaplan-10': {
    extendedTerms: [
      { term: 'Yerkes-Dodson Law', def: 'Performance follows an inverted-U over arousal; optimal arousal lower for difficult tasks, higher for simple ones.' },
      { term: 'Set Point Theory', def: 'Body defends a stable weight range; metabolism adjusts after dieting \u2014 explains diet failure.' },
      { term: 'Glucose & Hunger Signals', def: 'Blood glucose drop triggers hunger (liver signal); hypothalamus integrates: lateral = hunger center, ventromedial = satiety.' },
      { term: 'Sexual Response Cycle', def: 'Masters & Johnson: excitement, plateau, orgasm, resolution.' },
      { term: 'Achievement Motivation (nAch)', def: 'McClelland: TAT-measured need for achievement predicts entrepreneurial and goal-directed behavior.' },
      { term: 'Self-Determination Theory', def: 'Deci & Ryan: three innate needs \u2014 autonomy, competence, relatedness \u2014 drive intrinsic motivation.' },
      { term: 'Cannon-Bard Theory', def: 'Thalamus sends arousal and emotional experience SIMULTANEOUSLY \u2014 no ordering needed.' },
      { term: 'Misattribution of Arousal', def: 'Schachter-style: bridge study (Dutton & Aron) \u2014 arousal from scary bridge attributed to attraction.' },
      { term: 'Display Rules', def: 'Culture-specific norms governing when/how emotions are expressed (suppression in collectivist cultures).' },
      { term: 'Facial Feedback', def: 'Facial muscle activity feeds back into felt emotion; Botox studies show dampened emotion recognition/experience.' },
      { term: 'Projective Tests', def: 'Rorschach inkblots, TAT \u2014 ambiguous stimuli reveal unconscious dynamics; low reliability/validity but clinically used.' },
      { term: 'MMPI', def: 'Objective personality inventory with validity scales; empirically derived, used diagnostically.' },
      { term: 'Trait vs State', def: 'Traits = stable dispositions; states = temporary conditions. Trait theory predicts cross-situational consistency.' },
      { term: 'Bandura\u2019s Reciprocal Determinism', def: 'Person, behavior, and environment mutually influence one another (social-cognitive theory).' },
      { term: 'Self-Efficacy', def: 'Bandura: belief in one\u2019s capability to execute actions; predicts persistence and achievement beyond skill alone.' },
      { term: 'Spotlight Effect', def: 'Overestimating how much others notice our appearance and behavior.' },
    ],
    gateFocus: [
      'Emotion theory comparison chart is high-yield: ORDER of physiology vs experience vs appraisal for James-Lange, Cannon-Bard, Schachter-Singer, Lazarus, Zajonc (affect before cognition).',
      'Yerkes-Dodson: match task difficulty to optimal arousal \u2014 hard tasks need LOWER arousal.',
      'Motivation theories mapped to examples: eating (drive), money (incentive), curiosity (arousal), purpose (self-determination).',
      'Defense mechanisms tested by scenario \u2014 identify the mechanism, not the definition: projection = attributing YOUR impulse to OTHERS.',
      'Big Five dimensions correlate with real outcomes: conscientiousness \u2192 job performance; neuroticism \u2192 distress.',
    ],
    pitfalls: [
      'James-Lange gets the sequence backwards from intuition: bodily reaction FIRST, emotion as its interpretation.',
      'Schachter-Singer requires BOTH arousal and a label \u2014 adrenaline injection with no explanation produced context-dependent emotion.',
      'Id/superego conflicts are UNCONSCIOUS; ego operates across all three levels.',
      'Overjustification is about REWARD undermining intrinsic interest \u2014 punishment and reward behave differently.',
    ],
  },

  'kaplan-11': {
    extendedTerms: [
      { term: 'Rosenhan Study', def: '"Being sane in insane places": pseudopatients admitted to psychiatric wards; labels stick and color staff perception of normal behavior.' },
      { term: 'Generalized Anxiety vs Panic', def: 'GAD = constant diffuse worry; panic disorder = discrete surges of intense fear with inter-attack worry.' },
      { term: 'Agoraphobia', def: 'Fear of situations where escape might be difficult; frequently co-occurs with panic disorder.' },
      { term: 'Somatic Symptom Disorders', def: 'Distressing somatic complaints with excessive thoughts/feelings; distinct from factitious disorders (intentional) and malingering (external gain).' },
      { term: 'Dissociative Disorders', def: 'Disruption of identity/memory: dissociative amnesia, fugue, identity disorder (DID); strongly trauma-linked.' },
      { term: 'Mania Criteria', def: '\u22651 week elevated/irritable mood + grandiosity, decreased sleep need, pressured speech, racing thoughts, risky activity.' },
      { term: 'Learned Helplessness Model of Depression', def: 'Seligman: uncontrollable negative events \u2192 passivity; reformulated as pessimistic explanatory style (internal-stable-global).' },
      { term: 'Beck\u2019s Cognitive Triad', def: 'Depression maintained by negative views of self, world, and future; treated by identifying cognitive distortions.' },
      { term: 'DBT', def: 'Linehan\u2019s dialectical behavior therapy for borderline PD: mindfulness, distress tolerance, emotion regulation, interpersonal effectiveness.' },
      { term: 'Antidepressant Classes', def: 'SSRIs/SNRIs first-line; tricyclics and MAOIs effective but more side effects/dietary risks.' },
      { term: 'Tardive Dyskinesia', def: 'Involuntary movements from long-term typical antipsychotic use; atypicals carry lower risk.' },
      { term: 'Meta-Analysis & dodo-bird Verdict', def: 'Psychotherapy outcome research finds common factors (alliance, expectancy) rival specific techniques.' },
      { term: 'Evidence-Based Practice', def: 'Integration of best research evidence, clinical expertise, and patient values.' },
    ],
    gateFocus: [
      'Diagnosis questions hinge on DURATION and FUNCTIONALITY thresholds: MDD \u22652 weeks, GAD \u22656 months, mania \u22651 week.',
      'Symptom matching drill: obsessions (intrusive thoughts) vs delusions (false beliefs); hallucinations vs illusions (misperceived stimuli).',
      'Match treatment to disorder: OCD \u2192 ERP; phobia \u2192 systematic desensitization; BPD \u2192 DBT; bipolar \u2192 lithium; schizophrenia \u2192 antipsychotics.',
      'Cluster A/B/C personality disorder sorting appears regularly \u2014 know one example of each cluster.',
      'Diathesis-stress is the default model answer for "why do only some people develop disorder X after trauma?"',
    ],
    pitfalls: [
      'OCD is no longer classified under anxiety disorders in DSM-5 (own category) but remains anxiety-based conceptually.',
      'Negative symptoms are NOT absent in everyone and respond poorly to typical antipsychotics.',
      'Multiple personality disorder = dissociative identity disorder, NOT schizophrenia (split MIND vs split PERSONALITY confusion).',
      'ECT today is done under anesthesia with muscle relaxants \u2014 safe and effective for severe depression; stigma-based distractors abound.',
    ],
  },

  'kaplan-12': {
    extendedTerms: [
      { term: 'Elaboration Likelihood Model', def: 'Petty & Cacioppo: persuasion via central route (argument quality, durable change) vs peripheral route (cues, fleeting change).' },
      { term: 'Foot-in-the-Door Psychology', def: 'Works via SELF-PERCEPTION: "I agreed to the small request, so I must be helpful."' },
      { term: 'Door-in-the-Face Psychology', def: 'Works via RECIPROCITY norm: requester visibly concedes, target feels obligated to reciprocate.' },
      { term: 'Low-Ball Technique', def: 'Securing commitment with attractive terms, then withdrawing them \u2014 commitment persists.' },
      { term: 'That\u2019s-Not-All Technique', def: 'Adding a bonus before the target responds inflates perceived deal value.' },
      { term: 'Stanford Prison Experiment', def: 'Zimbardo: assigned guard/prisoner roles produced abusive behavior so quickly the study ended early; heavily criticized for demand characteristics and coaching.' },
      { term: 'Social Impact Theory', def: 'Conformity pressure = f(number of sources, strength/importance, immediacy).' },
      { term: 'Minority Influence', def: 'Consistent minorities can shift majorities (Moscovici) \u2014 conversion effect rather than compliance.' },
      { term: 'Superordinate Goals', def: 'Sherif\u2019s Robbers Cave: shared goals requiring cooperation reduce intergroup conflict.' },
      { term: 'Jigsaw Classroom', def: 'Aronson: cooperative interdependence reduces prejudice in schools.' },
      { term: 'Matching Hypothesis', def: 'People pair with partners of similar attractiveness; reciprocity of liking fuels attraction.' },
      { term: 'Passionate vs Companionate Love', def: 'Passionate: intense longing (Hatfield); companionate: deep affectionate attachment; Sternberg\u2019s triangle: intimacy + passion + commitment.' },
      { term: 'Group Polarization Mechanism', def: 'Persuasive arguments + social comparison amplify initial leanings in discussion.' },
      { term: 'Groupthink Prevention', def: 'Devil\u2019s advocate role, leader withholding opinion, outside experts, second-chance meetings.' },
      { term: 'Social Responsibility Norm', def: 'Expectation that people will help those dependent on them, even at cost.' },
      { term: 'Urban Overload Hypothesis', def: 'City dwellers help less because of stimulus overload, not callousness; helping rises when responsibility is personalized.' },
    ],
    gateFocus: [
      'Classic experiments map: Asch \u2192 conformity, Milgram \u2192 obedience, Zimbardo \u2192 roles/deindividuation, Sherif \u2192 superordinate goals/intergroup, Festinger \u2192 dissonance.',
      'Milgram variations: proximity of authority UP \u2192 obedience up; victim proximity UP \u2192 obedience down; dissenting ally present \u2192 obedience collapses.',
      'Normative (fit in) vs informational (be right) influence \u2014 identify which drives behavior in scenarios.',
      'Compliance technique questions require knowing the MECHANISM, not just the sequence.',
      'Reducing prejudice: contact works under conditions (equal status, cooperation, common goals, institutional support).',
    ],
    pitfalls: [
      'Deindividuation is loss of SELF-AWARENESS in groups; diffusion of responsibility explains BYSTANDER apathy \u2014 different constructs.',
      'FAE persists even when we KNOW the situation was constrained (quiz game studies).',
      'Attitudes weakly predict behavior (LaPiere study); behavior also changes attitudes (dissonance).',
      'Groupthink requires COHESION + insulation + directive leadership; cohesive groups without these don\u2019t necessarily fall into it.',
    ],
  },
};
