export const XH_C5_MSQ_TYPES = ["category-membership", "theory-audit", "adjacent-construct", "negation-exclusion", "vignette-application", "methods-statistics", "data-interpretation", "paired-contrast", "completion-matching", "scope-qualifier"];

export const XH_C5_MSQ_TYPE_ASSIGNMENTS = {
  "gate-style-anova-01": "methods-statistics",
  "gate-style-applications-02": "vignette-application",
  "gate-style-applications-04": "category-membership",
  "gate-style-applications-06": "category-membership",
  "gate-style-applications-08": "category-membership",
  "gate-style-applications-10": "vignette-application",
  "gate-style-bio-01": "category-membership",
  "gate-style-bio-02": "category-membership",
  "gate-style-clinical-01": "adjacent-construct",
  "gate-style-cognition-01": "vignette-application",
  "gate-style-cognition-02": "category-membership",
  "gate-style-coping-01": "vignette-application",
  "gate-style-development-01": "vignette-application",
  "gate-style-health-01": "category-membership",
  "gate-style-intergroup-01": "vignette-application",
  "gate-style-learning-01": "vignette-application",
  "gate-style-learning-02": "vignette-application",
  "gate-style-methods-01": "methods-statistics",
  "gate-style-methods-02": "methods-statistics",
  "gate-style-methods-03": "data-interpretation",
  "gate-style-methods-04": "methods-statistics",
  "gate-style-methods-05": "data-interpretation",
  "gate-style-motivation-01": "theory-audit",
  "gate-style-motivation-02": "theory-audit",
  "gate-style-org-02": "vignette-application",
  "gate-style-org-04": "theory-audit",
  "gate-style-org-06": "vignette-application",
  "gate-style-org-08": "theory-audit",
  "gate-style-org-10": "category-membership",
  "gate-style-personality-biology-01": "category-membership",
  "gate-style-physiology-01": "completion-matching",
  "gate-style-sensation-01": "methods-statistics",
  "gate-style-sensation-02": "category-membership",
  "gate-style-social-01": "vignette-application",
  "gate-style-social-02": "category-membership",
  "xh-c5-hard-v3-development-001": "adjacent-construct",
  "xh-c5-hard-v3-development-002": "data-interpretation",
  "xh-c5-hard-v3-development-003": "theory-audit",
  "xh-c5-hard-v3-development-004": "methods-statistics",
  "xh-c5-hard-v3-motivation-emotion-stress-001": "data-interpretation",
  "xh-c5-hard-v3-motivation-emotion-stress-002": "data-interpretation",
  "xh-c5-hard-v3-motivation-emotion-stress-003": "methods-statistics",
  "xh-c5-hard-v3-motivation-emotion-stress-004": "data-interpretation",
  "xh-c5-hard-v3-p1-001": "methods-statistics",
  "xh-c5-hard-v3-p1-002": "methods-statistics",
  "xh-c5-hard-v3-p1-003": "methods-statistics",
  "xh-c5-hard-v3-p1-004": "methods-statistics",
  "xh-c5-hard-v3-p1-005": "data-interpretation",
  "xh-c5-hard-v3-p1-006": "data-interpretation",
  "xh-c5-hard-v3-p1-007": "methods-statistics",
  "xh-c5-hard-v3-p1-008": "methods-statistics",
  "xh-c5-hard-v3-p1-009": "vignette-application",
  "xh-c5-hard-v3-p1-010": "vignette-application",
  "xh-c5-hard-v3-p1-011": "vignette-application",
  "xh-c5-hard-v3-p1-012": "data-interpretation",
  "xh-c5-hard-v3-p2-001": "data-interpretation",
  "xh-c5-hard-v3-p2-002": "vignette-application",
  "xh-c5-hard-v3-p2-003": "theory-audit",
  "xh-c5-hard-v3-p2-004": "data-interpretation",
  "xh-c5-hard-v3-p2-005": "data-interpretation",
  "xh-c5-hard-v3-p2-006": "methods-statistics",
  "xh-c5-hard-v3-p2-007": "data-interpretation",
  "xh-c5-hard-v3-p2-008": "paired-contrast",
  "xh-c5-hard-v3-p2-009": "data-interpretation",
  "xh-c5-hard-v3-p2-010": "methods-statistics",
  "xh-c5-hard-v3-p2-011": "methods-statistics",
  "xh-c5-hard-v3-p2-012": "methods-statistics",
  "xh-c5-hard-v3-p4-001": "vignette-application",
  "xh-c5-hard-v3-p4-002": "vignette-application",
  "xh-c5-hard-v3-p4-003": "methods-statistics",
  "xh-c5-hard-v3-p4-004": "vignette-application",
  "xh-c5-hard-v3-p4-005": "vignette-application",
  "xh-c5-hard-v3-p4-006": "methods-statistics",
  "xh-c5-hard-v3-p4-007": "vignette-application",
  "xh-c5-hard-v3-p4-008": "methods-statistics",
  "xh-c5-hard-v3-social-001": "data-interpretation",
  "xh-c5-hard-v3-social-002": "data-interpretation",
  "xh-c5-hard-v3-social-003": "vignette-application",
  "xh-c5-hard-v3-social-004": "methods-statistics",
  "xh-c5-msq-applications-001": "vignette-application",
  "xh-c5-msq-applications-002": "vignette-application",
  "xh-c5-msq-applications-003": "vignette-application",
  "xh-c5-msq-applications-004": "theory-audit",
  "xh-c5-msq-applications-005": "category-membership",
  "xh-c5-msq-applications-006": "vignette-application",
  "xh-c5-msq-applications-007": "vignette-application",
  "xh-c5-msq-applications-008": "methods-statistics",
  "xh-c5-msq-applications-009": "scope-qualifier",
  "xh-c5-msq-applications-010": "methods-statistics",
  "xh-c5-msq-applications-011": "category-membership",
  "xh-c5-msq-biological-evolutionary-001": "adjacent-construct",
  "xh-c5-msq-biological-evolutionary-002": "vignette-application",
  "xh-c5-msq-biological-evolutionary-003": "vignette-application",
  "xh-c5-msq-biological-evolutionary-004": "vignette-application",
  "xh-c5-msq-biological-evolutionary-005": "vignette-application",
  "xh-c5-msq-biological-evolutionary-006": "theory-audit",
  "xh-c5-msq-biological-evolutionary-007": "theory-audit",
  "xh-c5-msq-biological-evolutionary-008": "data-interpretation",
  "xh-c5-msq-biological-evolutionary-009": "vignette-application",
  "xh-c5-msq-biological-evolutionary-010": "vignette-application",
  "xh-c5-msq-biological-evolutionary-011": "paired-contrast",
  "xh-c5-msq-clinical-organizational-001": "vignette-application",
  "xh-c5-msq-clinical-organizational-002": "vignette-application",
  "xh-c5-msq-clinical-organizational-003": "vignette-application",
  "xh-c5-msq-clinical-organizational-004": "vignette-application",
  "xh-c5-msq-clinical-organizational-005": "methods-statistics",
  "xh-c5-msq-clinical-organizational-006": "category-membership",
  "xh-c5-msq-clinical-organizational-007": "methods-statistics",
  "xh-c5-msq-clinical-organizational-008": "completion-matching",
  "xh-c5-msq-clinical-organizational-009": "vignette-application",
  "xh-c5-msq-clinical-organizational-010": "methods-statistics",
  "xh-c5-msq-clinical-organizational-011": "category-membership",
  "xh-c5-msq-cognition-001": "vignette-application",
  "xh-c5-msq-cognition-002": "vignette-application",
  "xh-c5-msq-cognition-003": "data-interpretation",
  "xh-c5-msq-cognition-004": "scope-qualifier",
  "xh-c5-msq-cognition-005": "methods-statistics",
  "xh-c5-msq-cognition-006": "data-interpretation",
  "xh-c5-msq-cognition-007": "vignette-application",
  "xh-c5-msq-cognition-008": "theory-audit",
  "xh-c5-msq-cognition-009": "data-interpretation",
  "xh-c5-msq-cognition-010": "data-interpretation",
  "xh-c5-msq-cognition-011": "paired-contrast",
  "xh-c5-msq-development-001": "vignette-application",
  "xh-c5-msq-development-002": "vignette-application",
  "xh-c5-msq-development-003": "vignette-application",
  "xh-c5-msq-development-004": "vignette-application",
  "xh-c5-msq-development-005": "category-membership",
  "xh-c5-msq-development-006": "vignette-application",
  "xh-c5-msq-development-007": "category-membership",
  "xh-c5-msq-development-008": "data-interpretation",
  "xh-c5-msq-development-009": "adjacent-construct",
  "xh-c5-msq-development-010": "paired-contrast",
  "xh-c5-msq-development-011": "theory-audit",
  "xh-c5-msq-motivation-emotion-stress-001": "vignette-application",
  "xh-c5-msq-motivation-emotion-stress-002": "theory-audit",
  "xh-c5-msq-motivation-emotion-stress-003": "data-interpretation",
  "xh-c5-msq-motivation-emotion-stress-004": "category-membership",
  "xh-c5-msq-motivation-emotion-stress-005": "category-membership",
  "xh-c5-msq-motivation-emotion-stress-006": "theory-audit",
  "xh-c5-msq-motivation-emotion-stress-007": "theory-audit",
  "xh-c5-msq-motivation-emotion-stress-008": "methods-statistics",
  "xh-c5-msq-motivation-emotion-stress-009": "adjacent-construct",
  "xh-c5-msq-motivation-emotion-stress-010": "data-interpretation",
  "xh-c5-msq-motivation-emotion-stress-011": "category-membership",
  "xh-c5-msq-perception-learning-memory-001": "adjacent-construct",
  "xh-c5-msq-perception-learning-memory-002": "adjacent-construct",
  "xh-c5-msq-perception-learning-memory-003": "vignette-application",
  "xh-c5-msq-perception-learning-memory-004": "adjacent-construct",
  "xh-c5-msq-perception-learning-memory-005": "data-interpretation",
  "xh-c5-msq-perception-learning-memory-006": "data-interpretation",
  "xh-c5-msq-perception-learning-memory-007": "vignette-application",
  "xh-c5-msq-perception-learning-memory-008": "data-interpretation",
  "xh-c5-msq-perception-learning-memory-009": "adjacent-construct",
  "xh-c5-msq-perception-learning-memory-010": "data-interpretation",
  "xh-c5-msq-perception-learning-memory-011": "adjacent-construct",
  "xh-c5-msq-personality-001": "data-interpretation",
  "xh-c5-msq-personality-002": "category-membership",
  "xh-c5-msq-personality-003": "paired-contrast",
  "xh-c5-msq-personality-004": "paired-contrast",
  "xh-c5-msq-personality-005": "completion-matching",
  "xh-c5-msq-personality-006": "theory-audit",
  "xh-c5-msq-personality-007": "theory-audit",
  "xh-c5-msq-personality-008": "methods-statistics",
  "xh-c5-msq-personality-009": "scope-qualifier",
  "xh-c5-msq-personality-010": "vignette-application",
  "xh-c5-msq-personality-011": "scope-qualifier",
  "xh-c5-msq-psychometrics-001": "adjacent-construct",
  "xh-c5-msq-psychometrics-002": "methods-statistics",
  "xh-c5-msq-psychometrics-003": "methods-statistics",
  "xh-c5-msq-psychometrics-004": "methods-statistics",
  "xh-c5-msq-psychometrics-005": "data-interpretation",
  "xh-c5-msq-psychometrics-006": "data-interpretation",
  "xh-c5-msq-psychometrics-007": "methods-statistics",
  "xh-c5-msq-psychometrics-008": "data-interpretation",
  "xh-c5-msq-psychometrics-009": "data-interpretation",
  "xh-c5-msq-psychometrics-010": "methods-statistics",
  "xh-c5-msq-psychometrics-011": "data-interpretation",
  "xh-c5-msq-research-methods-statistics-001": "methods-statistics",
  "xh-c5-msq-research-methods-statistics-002": "methods-statistics",
  "xh-c5-msq-research-methods-statistics-003": "methods-statistics",
  "xh-c5-msq-research-methods-statistics-004": "data-interpretation",
  "xh-c5-msq-research-methods-statistics-005": "data-interpretation",
  "xh-c5-msq-research-methods-statistics-006": "methods-statistics",
  "xh-c5-msq-research-methods-statistics-007": "methods-statistics",
  "xh-c5-msq-research-methods-statistics-008": "methods-statistics",
  "xh-c5-msq-research-methods-statistics-009": "data-interpretation",
  "xh-c5-msq-research-methods-statistics-010": "methods-statistics",
  "xh-c5-msq-research-methods-statistics-011": "data-interpretation",
  "xh-c5-msq-social-001": "vignette-application",
  "xh-c5-msq-social-002": "vignette-application",
  "xh-c5-msq-social-003": "theory-audit",
  "xh-c5-msq-social-004": "vignette-application",
  "xh-c5-msq-social-005": "theory-audit",
  "xh-c5-msq-social-006": "vignette-application",
  "xh-c5-msq-social-007": "vignette-application",
  "xh-c5-msq-social-008": "category-membership",
  "xh-c5-msq-social-009": "vignette-application",
  "xh-c5-msq-social-010": "theory-audit",
  "xh-c5-msq-social-011": "theory-audit"
};

export function msqTypesForCycle(cycleIndex = 0) {
  const normalized = ((Number(cycleIndex) || 0) % 5 + 5) % 5;
  const start = (normalized * 4) % XH_C5_MSQ_TYPES.length;
  return Array.from({ length: 4 }, (_, offset) => (
    XH_C5_MSQ_TYPES[(start + offset) % XH_C5_MSQ_TYPES.length]
  ));
}

export function orderedMsqTypesForAvailableCycle(cycleIndex = 0, availableTypes = XH_C5_MSQ_TYPES) {
  const available = availableTypes instanceof Set ? availableTypes : new Set(availableTypes);
  const normalized = ((Number(cycleIndex) || 0) % 5 + 5) % 5;
  const start = (normalized * 4) % XH_C5_MSQ_TYPES.length;
  const selected = [];
  for (let offset = 0; offset < XH_C5_MSQ_TYPES.length; offset += 1) {
    const type = XH_C5_MSQ_TYPES[(start + offset) % XH_C5_MSQ_TYPES.length];
    if (available.has(type)) selected.push(type);
  }
  return selected;
}

export function msqTypesForAvailableCycle(cycleIndex = 0, availableTypes = XH_C5_MSQ_TYPES) {
  const selected = orderedMsqTypesForAvailableCycle(cycleIndex, availableTypes).slice(0, 4);
  if (selected.length < 4) {
    throw new Error(`At least four MSQ structures are required; found ${selected.length}`);
  }
  return selected;
}

export function attachMsqType(question) {
  if (question?.type !== 'MSQ') return question;
  const msqType = question.msqType || XH_C5_MSQ_TYPE_ASSIGNMENTS[question.id];
  return msqType ? { ...question, msqType } : question;
}
