export const XH_C5_MSQ_ARCHETYPE_EXPANSION = [
  {
    id: 'xh-c5-msq-archetype-negation-001',
    type: 'MSQ',
    topic: 'research-methods-statistics',
    marks: 1,
    msqType: 'negation-exclusion',
    question: 'An ethics committee reviews a low-risk study that withholds its precise hypothesis until participation ends. Which proposed actions would NOT satisfy ordinary safeguards for research deception?',
    options: {
      A: 'Explain the withheld information during a timely debriefing after participation.',
      B: 'Omit debriefing because explaining the procedure would be inconvenient for the research team.',
      C: 'Allow a participant to withdraw their data after learning the study’s actual purpose.',
      D: 'Conceal a foreseeable serious risk because revealing it might reduce recruitment.',
    },
    answers: ['B', 'D'],
    explanation: 'A: Incorrect selection — timely debriefing is an ordinary safeguard. B: Correct selection — convenience does not justify omitting an appropriate debriefing. C: Incorrect selection — post-debrief withdrawal can protect autonomy. D: Correct selection — material foreseeable risk cannot be hidden merely to improve recruitment.',
  },
  {
    id: 'xh-c5-msq-archetype-negation-002',
    type: 'MSQ',
    topic: 'clinical-organizational',
    marks: 2,
    msqType: 'negation-exclusion',
    question: 'A client reports recurrent surges of fear, palpitations and avoidance of crowded transport, but the assessment has not yet examined substance use, medical causes or the pattern of anticipatory worry. Which conclusions are NOT warranted from the available information?',
    options: {
      A: 'The symptom report by itself establishes a definitive panic-disorder diagnosis.',
      B: 'Medical and substance-related explanations still require assessment.',
      C: 'The function and extent of the avoidance are relevant to differential diagnosis.',
      D: 'A normal cardiac examination would by itself prove that the episodes have a psychological cause.',
    },
    answers: ['A', 'D'],
    explanation: 'A: Correct selection — a definitive diagnosis requires fuller assessment and exclusion of alternatives. B: Incorrect selection — those explanations remain relevant. C: Incorrect selection — avoidance and anticipatory processes help distinguish related conditions. D: Correct selection — excluding one medical account does not prove a uniquely psychological cause.',
  },
  {
    id: 'xh-c5-msq-archetype-matching-001',
    type: 'MSQ',
    topic: 'perception-learning-memory',
    marks: 1,
    msqType: 'completion-matching',
    question: 'A memory researcher links each observed performance pattern with the process that most directly accounts for it. Which observation–process pairings are appropriate?',
    options: {
      A: 'Better recall after connecting new material with prior knowledge — elaborative encoding.',
      B: 'Improved recall when the original learning environment is reinstated — context-dependent retrieval.',
      C: 'Old password habits disrupt recall of a recently changed password — proactive interference.',
      D: 'A recently learned phone number disrupts recall of an older number — proactive interference.',
    },
    answers: ['A', 'B', 'C'],
    explanation: 'A: Correct — elaboration creates meaningful retrieval routes. B: Correct — reinstated context can provide effective retrieval cues. C: Correct — older learning interfering with newer learning is proactive interference. D: Incorrect — newer learning disrupting older learning is retroactive interference.',
  },
  {
    id: 'xh-c5-msq-archetype-scope-001',
    type: 'MSQ',
    topic: 'research-methods-statistics',
    marks: 2,
    msqType: 'scope-qualifier',
    question: 'A randomized study estimates a small treatment effect whose confidence interval includes zero as well as effects of practical importance in either direction. Which interpretations respect the scope of this result?',
    options: {
      A: 'The data do not establish that the population effect is exactly zero.',
      B: 'The interval leaves both modest benefit and modest harm compatible with the estimate.',
      C: 'Failure to reject the null proves that the treatment has no practically important effect.',
      D: 'A larger, more precise study could narrow the range of effects compatible with the data.',
    },
    answers: ['A', 'B', 'D'],
    explanation: 'A: Correct — non-rejection does not prove an exact zero effect. B: Correct — the interval explicitly retains effects in both directions. C: Incorrect — absence of statistical rejection is not proof of practical equivalence. D: Correct — increased precision can narrow the confidence interval.',
  },
  {
    id: 'xh-c5-msq-archetype-theory-001',
    type: 'MSQ',
    topic: 'psychometrics',
    marks: 1,
    msqType: 'theory-audit',
    question: 'A testing team interprets scores using classical test theory before revising a short aptitude scale. Which claims are compatible with that framework?',
    options: {
      A: 'An observed score is represented as a true-score component plus error.',
      B: 'Reliability concerns the proportion of observed-score variance attributable to true-score variance.',
      C: 'A person’s true score is assumed to change every time an item is administered.',
      D: 'Random measurement error can reduce the consistency of observed scores.',
    },
    answers: ['A', 'B', 'D'],
    explanation: 'A: Correct — classical test theory decomposes observed score into true score and error. B: Correct — reliability is expressed through the true-score share of observed variance. C: Incorrect — the model does not define true score as changing on every administration. D: Correct — random error lowers score consistency.',
  },
  {
    id: 'xh-c5-msq-archetype-adjacent-001',
    type: 'MSQ',
    topic: 'social',
    marks: 1,
    msqType: 'adjacent-construct',
    question: 'A student publicly agrees with an obviously incorrect unanimous group but privately retains the original answer. In a second unfamiliar task, the student accepts the group’s judgment as probably accurate. Which distinctions fit the two responses?',
    options: {
      A: 'The first response is consistent with normative social influence.',
      B: 'The first response demonstrates private acceptance produced by informational influence.',
      C: 'The second response is consistent with informational social influence.',
      D: 'The second response must be obedience because other people affected the judgment.',
    },
    answers: ['A', 'C'],
    explanation: 'A: Correct — public agreement without private acceptance fits normative pressure. B: Incorrect — the retained private answer argues against informational acceptance. C: Correct — uncertainty can make the group a source of information. D: Incorrect — social influence is not automatically obedience to authority.',
  },
];
